import ceylon.test{test,assertEquals}
import ceylon.markdown.core{parse}
import ceylon.markdown.html{renderPartialHtml}
import ceylon.html{renderTemplate,Node}

/*
  The code in this file was generated by the make_tests.py script
  You might want to run it from time to time
  to keep these tests up to date with the latest
  commonmark spec tests
*/
shared class ATX_headings() {
    String render(String md) {
        value sb = StringBuilder();
        value f = sb.append;
        for (node in renderPartialHtml(parse(md))) {
            assert(is Node node);
            renderTemplate(node, f);
        }
        return sb.string;
    }

    """Test for example 32 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-32"""
    test
    shared void specTest_ATX_headings_32() {
        value md = "# foo\n## foo\n### foo\n#### foo\n##### foo\n###### foo\n";
        value html = "<h1>foo</h1>\n<h2>foo</h2>\n<h3>foo</h3>\n<h4>foo</h4>\n<h5>foo</h5>\n<h6>foo</h6>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 33 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-33"""
    test
    shared void specTest_ATX_headings_33() {
        value md = "####### foo\n";
        value html = "<p>####### foo</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 34 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-34"""
    test
    shared void specTest_ATX_headings_34() {
        value md = "#5 bolt\n\n#hashtag\n";
        value html = "<p>#5 bolt</p>\n<p>#hashtag</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 35 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-35"""
    test
    shared void specTest_ATX_headings_35() {
        value md = "\\## foo\n";
        value html = "<p>## foo</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 36 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-36"""
    test
    shared void specTest_ATX_headings_36() {
        value md = "# foo *bar* \\*baz\\*\n";
        value html = "<h1>foo <em>bar</em> *baz*</h1>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 37 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-37"""
    test
    shared void specTest_ATX_headings_37() {
        value md = "#                  foo                     \n";
        value html = "<h1>foo</h1>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 38 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-38"""
    test
    shared void specTest_ATX_headings_38() {
        value md = " ### foo\n  ## foo\n   # foo\n";
        value html = "<h3>foo</h3>\n<h2>foo</h2>\n<h1>foo</h1>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 39 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-39"""
    test
    shared void specTest_ATX_headings_39() {
        value md = "    # foo\n";
        value html = "<pre><code># foo\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 40 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-40"""
    test
    shared void specTest_ATX_headings_40() {
        value md = "foo\n    # bar\n";
        value html = "<p>foo\n# bar</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 41 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-41"""
    test
    shared void specTest_ATX_headings_41() {
        value md = "## foo ##\n  ###   bar    ###\n";
        value html = "<h2>foo</h2>\n<h3>bar</h3>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 42 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-42"""
    test
    shared void specTest_ATX_headings_42() {
        value md = "# foo ##################################\n##### foo ##\n";
        value html = "<h1>foo</h1>\n<h5>foo</h5>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 43 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-43"""
    test
    shared void specTest_ATX_headings_43() {
        value md = "### foo ###     \n";
        value html = "<h3>foo</h3>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 44 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-44"""
    test
    shared void specTest_ATX_headings_44() {
        value md = "### foo ### b\n";
        value html = "<h3>foo ### b</h3>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 45 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-45"""
    test
    shared void specTest_ATX_headings_45() {
        value md = "# foo#\n";
        value html = "<h1>foo#</h1>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 46 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-46"""
    test
    shared void specTest_ATX_headings_46() {
        value md = "### foo \\###\n## foo #\\##\n# foo \\#\n";
        value html = "<h3>foo ###</h3>\n<h2>foo ###</h2>\n<h1>foo #</h1>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 47 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-47"""
    test
    shared void specTest_ATX_headings_47() {
        value md = "****\n## foo\n****\n";
        value html = "<hr />\n<h2>foo</h2>\n<hr />\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 48 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-48"""
    test
    shared void specTest_ATX_headings_48() {
        value md = "Foo bar\n# baz\nBar foo\n";
        value html = "<p>Foo bar</p>\n<h1>baz</h1>\n<p>Bar foo</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 49 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-49"""
    test
    shared void specTest_ATX_headings_49() {
        value md = "## \n#\n### ###\n";
        value html = "<h2></h2>\n<h1></h1>\n<h3></h3>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

}
