import ceylon.test{test,assertEquals}
import ceylon.markdown.core{parse}
import ceylon.markdown.html{renderPartialHtml}
import ceylon.html{renderTemplate,Node}

/*
  The code in this file was generated by the make_tests.py script
  You might want to run it from time to time
  to keep these tests up to date with the latest
  commonmark spec tests
*/
shared class Autolinks() {
    String render(String md) {
        value sb = StringBuilder();
        value f = sb.append;
        for (node in renderPartialHtml(parse(md))) {
            assert(is Node node);
            renderTemplate(node, f);
        }
        return sb.string;
    }

    """Test for example 560 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-560"""
    test
    shared void specTest_Autolinks_560() {
        value md = "<http://foo.bar.baz>\n";
        value html = "<p><a href=\"http://foo.bar.baz\">http://foo.bar.baz</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 561 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-561"""
    test
    shared void specTest_Autolinks_561() {
        value md = "<http://foo.bar.baz/test?q=hello&id=22&boolean>\n";
        value html = "<p><a href=\"http://foo.bar.baz/test?q=hello&amp;id=22&amp;boolean\">http://foo.bar.baz/test?q=hello&amp;id=22&amp;boolean</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 562 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-562"""
    test
    shared void specTest_Autolinks_562() {
        value md = "<irc://foo.bar:2233/baz>\n";
        value html = "<p><a href=\"irc://foo.bar:2233/baz\">irc://foo.bar:2233/baz</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 563 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-563"""
    test
    shared void specTest_Autolinks_563() {
        value md = "<MAILTO:FOO@BAR.BAZ>\n";
        value html = "<p><a href=\"MAILTO:FOO@BAR.BAZ\">MAILTO:FOO@BAR.BAZ</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 564 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-564"""
    test
    shared void specTest_Autolinks_564() {
        value md = "<a+b+c:d>\n";
        value html = "<p><a href=\"a+b+c:d\">a+b+c:d</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 565 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-565"""
    test
    shared void specTest_Autolinks_565() {
        value md = "<made-up-scheme://foo,bar>\n";
        value html = "<p><a href=\"made-up-scheme://foo,bar\">made-up-scheme://foo,bar</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 566 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-566"""
    test
    shared void specTest_Autolinks_566() {
        value md = "<http://../>\n";
        value html = "<p><a href=\"http://../\">http://../</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 567 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-567"""
    test
    shared void specTest_Autolinks_567() {
        value md = "<localhost:5001/foo>\n";
        value html = "<p><a href=\"localhost:5001/foo\">localhost:5001/foo</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 568 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-568"""
    test
    shared void specTest_Autolinks_568() {
        value md = "<http://foo.bar/baz bim>\n";
        value html = "<p>&lt;http://foo.bar/baz bim&gt;</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 569 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-569"""
    test
    shared void specTest_Autolinks_569() {
        value md = "<http://example.com/\\[\\>\n";
        value html = "<p><a href=\"http://example.com/%5C%5B%5C\">http://example.com/\\[\\</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 570 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-570"""
    test
    shared void specTest_Autolinks_570() {
        value md = "<foo@bar.example.com>\n";
        value html = "<p><a href=\"mailto:foo@bar.example.com\">foo@bar.example.com</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 571 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-571"""
    test
    shared void specTest_Autolinks_571() {
        value md = "<foo+special@Bar.baz-bar0.com>\n";
        value html = "<p><a href=\"mailto:foo+special@Bar.baz-bar0.com\">foo+special@Bar.baz-bar0.com</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 572 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-572"""
    test
    shared void specTest_Autolinks_572() {
        value md = "<foo\\+@bar.example.com>\n";
        value html = "<p>&lt;foo+@bar.example.com&gt;</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 573 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-573"""
    test
    shared void specTest_Autolinks_573() {
        value md = "<>\n";
        value html = "<p>&lt;&gt;</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 574 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-574"""
    test
    shared void specTest_Autolinks_574() {
        value md = "< http://foo.bar >\n";
        value html = "<p>&lt; http://foo.bar &gt;</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 575 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-575"""
    test
    shared void specTest_Autolinks_575() {
        value md = "<m:abc>\n";
        value html = "<p>&lt;m:abc&gt;</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 576 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-576"""
    test
    shared void specTest_Autolinks_576() {
        value md = "<foo.bar.baz>\n";
        value html = "<p>&lt;foo.bar.baz&gt;</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 577 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-577"""
    test
    shared void specTest_Autolinks_577() {
        value md = "http://example.com\n";
        value html = "<p>http://example.com</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 578 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-578"""
    test
    shared void specTest_Autolinks_578() {
        value md = "foo@bar.example.com\n";
        value html = "<p>foo@bar.example.com</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

}
