import ceylon.test{test,assertEquals}
import ceylon.markdown.core{parse}
import ceylon.markdown.html{renderPartialHtml}
import ceylon.html{renderTemplate,Node}

/*
  The code in this file was generated by the make_tests.py script
  You might want to run it from time to time
  to keep these tests up to date with the latest
  commonmark spec tests
*/
shared class Emphasis_and_strong_emphasis() {
    String render(String md) {
        value sb = StringBuilder();
        value f = sb.append;
        for (node in renderPartialHtml(parse(md))) {
            assert(is Node node);
            renderTemplate(node, f);
        }
        return sb.string;
    }

    """Test for example 328 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-328"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_328() {
        value md = "*foo bar*\n";
        value html = "<p><em>foo bar</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 329 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-329"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_329() {
        value md = "a * foo bar*\n";
        value html = "<p>a * foo bar*</p>\n";
        assertEquals{
            expected = html;
            actual = "Infinite loop";//TODOrender(md);
        };
    }

    """Test for example 330 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-330"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_330() {
        value md = "a*\"foo\"*\n";
        value html = "<p>a*&quot;foo&quot;*</p>\n";
        assertEquals{
            expected = html;
            actual = "Infinite loop";//TODOrender(md);
        };
    }

    """Test for example 331 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-331"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_331() {
        value md = "* a *\n";
        value html = "<p>* a *</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 332 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-332"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_332() {
        value md = "foo*bar*\n";
        value html = "<p>foo<em>bar</em></p>\n";
        assertEquals{
            expected = html;
            actual = "Infinite loop";//TODOrender(md);
        };
    }

    """Test for example 333 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-333"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_333() {
        value md = "5*6*78\n";
        value html = "<p>5<em>6</em>78</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 334 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-334"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_334() {
        value md = "_foo bar_\n";
        value html = "<p><em>foo bar</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 335 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-335"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_335() {
        value md = "_ foo bar_\n";
        value html = "<p>_ foo bar_</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 336 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-336"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_336() {
        value md = "a_\"foo\"_\n";
        value html = "<p>a_&quot;foo&quot;_</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 337 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-337"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_337() {
        value md = "foo_bar_\n";
        value html = "<p>foo_bar_</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 338 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-338"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_338() {
        value md = "5_6_78\n";
        value html = "<p>5_6_78</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 339 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-339"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_339() {
        value md = "пристаням_стремятся_\n";
        value html = "<p>пристаням_стремятся_</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 340 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-340"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_340() {
        value md = "aa_\"bb\"_cc\n";
        value html = "<p>aa_&quot;bb&quot;_cc</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 341 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-341"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_341() {
        value md = "foo-_(bar)_\n";
        value html = "<p>foo-<em>(bar)</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 342 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-342"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_342() {
        value md = "_foo*\n";
        value html = "<p>_foo*</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 343 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-343"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_343() {
        value md = "*foo bar *\n";
        value html = "<p>*foo bar *</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 344 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-344"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_344() {
        value md = "*foo bar\n*\n";
        value html = "<p>*foo bar\n*</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 345 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-345"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_345() {
        value md = "*(*foo)\n";
        value html = "<p>*(*foo)</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 346 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-346"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_346() {
        value md = "*(*foo*)*\n";
        value html = "<p><em>(<em>foo</em>)</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 347 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-347"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_347() {
        value md = "*foo*bar\n";
        value html = "<p><em>foo</em>bar</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 348 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-348"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_348() {
        value md = "_foo bar _\n";
        value html = "<p>_foo bar _</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 349 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-349"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_349() {
        value md = "_(_foo)\n";
        value html = "<p>_(_foo)</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 350 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-350"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_350() {
        value md = "_(_foo_)_\n";
        value html = "<p><em>(<em>foo</em>)</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 351 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-351"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_351() {
        value md = "_foo_bar\n";
        value html = "<p>_foo_bar</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 352 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-352"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_352() {
        value md = "_пристаням_стремятся\n";
        value html = "<p>_пристаням_стремятся</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 353 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-353"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_353() {
        value md = "_foo_bar_baz_\n";
        value html = "<p><em>foo_bar_baz</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 354 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-354"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_354() {
        value md = "_(bar)_.\n";
        value html = "<p><em>(bar)</em>.</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 355 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-355"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_355() {
        value md = "**foo bar**\n";
        value html = "<p><strong>foo bar</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 356 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-356"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_356() {
        value md = "** foo bar**\n";
        value html = "<p>** foo bar**</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 357 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-357"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_357() {
        value md = "a**\"foo\"**\n";
        value html = "<p>a**&quot;foo&quot;**</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 358 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-358"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_358() {
        value md = "foo**bar**\n";
        value html = "<p>foo<strong>bar</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 359 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-359"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_359() {
        value md = "__foo bar__\n";
        value html = "<p><strong>foo bar</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 360 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-360"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_360() {
        value md = "__ foo bar__\n";
        value html = "<p>__ foo bar__</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 361 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-361"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_361() {
        value md = "__\nfoo bar__\n";
        value html = "<p>__\nfoo bar__</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 362 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-362"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_362() {
        value md = "a__\"foo\"__\n";
        value html = "<p>a__&quot;foo&quot;__</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 363 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-363"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_363() {
        value md = "foo__bar__\n";
        value html = "<p>foo__bar__</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 364 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-364"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_364() {
        value md = "5__6__78\n";
        value html = "<p>5__6__78</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 365 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-365"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_365() {
        value md = "пристаням__стремятся__\n";
        value html = "<p>пристаням__стремятся__</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 366 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-366"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_366() {
        value md = "__foo, __bar__, baz__\n";
        value html = "<p><strong>foo, <strong>bar</strong>, baz</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 367 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-367"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_367() {
        value md = "foo-__(bar)__\n";
        value html = "<p>foo-<strong>(bar)</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 368 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-368"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_368() {
        value md = "**foo bar **\n";
        value html = "<p>**foo bar **</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 369 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-369"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_369() {
        value md = "**(**foo)\n";
        value html = "<p>**(**foo)</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 370 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-370"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_370() {
        value md = "*(**foo**)*\n";
        value html = "<p><em>(<strong>foo</strong>)</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 371 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-371"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_371() {
        value md = "**Gomphocarpus (*Gomphocarpus physocarpus*, syn.\n*Asclepias physocarpa*)**\n";
        value html = "<p><strong>Gomphocarpus (<em>Gomphocarpus physocarpus</em>, syn.\n<em>Asclepias physocarpa</em>)</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 372 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-372"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_372() {
        value md = "**foo \"*bar*\" foo**\n";
        value html = "<p><strong>foo &quot;<em>bar</em>&quot; foo</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 373 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-373"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_373() {
        value md = "**foo**bar\n";
        value html = "<p><strong>foo</strong>bar</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 374 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-374"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_374() {
        value md = "__foo bar __\n";
        value html = "<p>__foo bar __</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 375 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-375"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_375() {
        value md = "__(__foo)\n";
        value html = "<p>__(__foo)</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 376 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-376"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_376() {
        value md = "_(__foo__)_\n";
        value html = "<p><em>(<strong>foo</strong>)</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 377 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-377"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_377() {
        value md = "__foo__bar\n";
        value html = "<p>__foo__bar</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 378 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-378"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_378() {
        value md = "__пристаням__стремятся\n";
        value html = "<p>__пристаням__стремятся</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 379 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-379"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_379() {
        value md = "__foo__bar__baz__\n";
        value html = "<p><strong>foo__bar__baz</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 380 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-380"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_380() {
        value md = "__(bar)__.\n";
        value html = "<p><strong>(bar)</strong>.</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 381 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-381"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_381() {
        value md = "*foo [bar](/url)*\n";
        value html = "<p><em>foo <a href=\"/url\">bar</a></em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 382 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-382"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_382() {
        value md = "*foo\nbar*\n";
        value html = "<p><em>foo\nbar</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 383 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-383"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_383() {
        value md = "_foo __bar__ baz_\n";
        value html = "<p><em>foo <strong>bar</strong> baz</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 384 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-384"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_384() {
        value md = "_foo _bar_ baz_\n";
        value html = "<p><em>foo <em>bar</em> baz</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 385 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-385"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_385() {
        value md = "__foo_ bar_\n";
        value html = "<p><em><em>foo</em> bar</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 386 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-386"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_386() {
        value md = "*foo *bar**\n";
        value html = "<p><em>foo <em>bar</em></em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 387 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-387"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_387() {
        value md = "*foo **bar** baz*\n";
        value html = "<p><em>foo <strong>bar</strong> baz</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 388 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-388"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_388() {
        value md = "*foo**bar**baz*\n";
        value html = "<p><em>foo<strong>bar</strong>baz</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 389 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-389"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_389() {
        value md = "***foo** bar*\n";
        value html = "<p><em><strong>foo</strong> bar</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 390 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-390"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_390() {
        value md = "*foo **bar***\n";
        value html = "<p><em>foo <strong>bar</strong></em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 391 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-391"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_391() {
        value md = "*foo**bar***\n";
        value html = "<p><em>foo<strong>bar</strong></em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 392 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-392"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_392() {
        value md = "*foo**bar***\n";
        value html = "<p><em>foo<strong>bar</strong></em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 393 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-393"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_393() {
        value md = "*foo **bar *baz* bim** bop*\n";
        value html = "<p><em>foo <strong>bar <em>baz</em> bim</strong> bop</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 394 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-394"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_394() {
        value md = "*foo [*bar*](/url)*\n";
        value html = "<p><em>foo <a href=\"/url\"><em>bar</em></a></em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 395 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-395"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_395() {
        value md = "** is not an empty emphasis\n";
        value html = "<p>** is not an empty emphasis</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 396 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-396"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_396() {
        value md = "**** is not an empty strong emphasis\n";
        value html = "<p>**** is not an empty strong emphasis</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 397 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-397"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_397() {
        value md = "**foo [bar](/url)**\n";
        value html = "<p><strong>foo <a href=\"/url\">bar</a></strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 398 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-398"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_398() {
        value md = "**foo\nbar**\n";
        value html = "<p><strong>foo\nbar</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 399 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-399"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_399() {
        value md = "__foo _bar_ baz__\n";
        value html = "<p><strong>foo <em>bar</em> baz</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 400 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-400"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_400() {
        value md = "__foo __bar__ baz__\n";
        value html = "<p><strong>foo <strong>bar</strong> baz</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 401 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-401"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_401() {
        value md = "____foo__ bar__\n";
        value html = "<p><strong><strong>foo</strong> bar</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 402 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-402"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_402() {
        value md = "**foo **bar****\n";
        value html = "<p><strong>foo <strong>bar</strong></strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 403 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-403"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_403() {
        value md = "**foo *bar* baz**\n";
        value html = "<p><strong>foo <em>bar</em> baz</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 404 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-404"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_404() {
        value md = "**foo*bar*baz**\n";
        value html = "<p><strong>foo<em>bar</em>baz</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 405 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-405"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_405() {
        value md = "***foo* bar**\n";
        value html = "<p><strong><em>foo</em> bar</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 406 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-406"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_406() {
        value md = "**foo *bar***\n";
        value html = "<p><strong>foo <em>bar</em></strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 407 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-407"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_407() {
        value md = "**foo *bar **baz**\nbim* bop**\n";
        value html = "<p><strong>foo <em>bar <strong>baz</strong>\nbim</em> bop</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 408 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-408"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_408() {
        value md = "**foo [*bar*](/url)**\n";
        value html = "<p><strong>foo <a href=\"/url\"><em>bar</em></a></strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 409 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-409"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_409() {
        value md = "__ is not an empty emphasis\n";
        value html = "<p>__ is not an empty emphasis</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 410 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-410"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_410() {
        value md = "____ is not an empty strong emphasis\n";
        value html = "<p>____ is not an empty strong emphasis</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 411 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-411"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_411() {
        value md = "foo ***\n";
        value html = "<p>foo ***</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 412 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-412"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_412() {
        value md = "foo *\\**\n";
        value html = "<p>foo <em>*</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 413 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-413"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_413() {
        value md = "foo *_*\n";
        value html = "<p>foo <em>_</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 414 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-414"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_414() {
        value md = "foo *****\n";
        value html = "<p>foo *****</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 415 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-415"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_415() {
        value md = "foo **\\***\n";
        value html = "<p>foo <strong>*</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 416 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-416"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_416() {
        value md = "foo **_**\n";
        value html = "<p>foo <strong>_</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 417 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-417"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_417() {
        value md = "**foo*\n";
        value html = "<p>*<em>foo</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 418 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-418"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_418() {
        value md = "*foo**\n";
        value html = "<p><em>foo</em>*</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 419 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-419"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_419() {
        value md = "***foo**\n";
        value html = "<p>*<strong>foo</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 420 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-420"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_420() {
        value md = "****foo*\n";
        value html = "<p>***<em>foo</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 421 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-421"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_421() {
        value md = "**foo***\n";
        value html = "<p><strong>foo</strong>*</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 422 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-422"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_422() {
        value md = "*foo****\n";
        value html = "<p><em>foo</em>***</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 423 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-423"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_423() {
        value md = "foo ___\n";
        value html = "<p>foo ___</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 424 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-424"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_424() {
        value md = "foo _\\__\n";
        value html = "<p>foo <em>_</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 425 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-425"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_425() {
        value md = "foo _*_\n";
        value html = "<p>foo <em>*</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 426 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-426"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_426() {
        value md = "foo _____\n";
        value html = "<p>foo _____</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 427 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-427"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_427() {
        value md = "foo __\\___\n";
        value html = "<p>foo <strong>_</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 428 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-428"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_428() {
        value md = "foo __*__\n";
        value html = "<p>foo <strong>*</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 429 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-429"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_429() {
        value md = "__foo_\n";
        value html = "<p>_<em>foo</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 430 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-430"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_430() {
        value md = "_foo__\n";
        value html = "<p><em>foo</em>_</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 431 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-431"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_431() {
        value md = "___foo__\n";
        value html = "<p>_<strong>foo</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 432 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-432"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_432() {
        value md = "____foo_\n";
        value html = "<p>___<em>foo</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 433 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-433"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_433() {
        value md = "__foo___\n";
        value html = "<p><strong>foo</strong>_</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 434 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-434"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_434() {
        value md = "_foo____\n";
        value html = "<p><em>foo</em>___</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 435 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-435"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_435() {
        value md = "**foo**\n";
        value html = "<p><strong>foo</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 436 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-436"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_436() {
        value md = "*_foo_*\n";
        value html = "<p><em><em>foo</em></em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 437 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-437"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_437() {
        value md = "__foo__\n";
        value html = "<p><strong>foo</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 438 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-438"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_438() {
        value md = "_*foo*_\n";
        value html = "<p><em><em>foo</em></em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 439 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-439"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_439() {
        value md = "****foo****\n";
        value html = "<p><strong><strong>foo</strong></strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 440 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-440"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_440() {
        value md = "____foo____\n";
        value html = "<p><strong><strong>foo</strong></strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 441 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-441"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_441() {
        value md = "******foo******\n";
        value html = "<p><strong><strong><strong>foo</strong></strong></strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 442 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-442"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_442() {
        value md = "***foo***\n";
        value html = "<p><strong><em>foo</em></strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 443 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-443"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_443() {
        value md = "_____foo_____\n";
        value html = "<p><strong><strong><em>foo</em></strong></strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 444 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-444"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_444() {
        value md = "*foo _bar* baz_\n";
        value html = "<p><em>foo _bar</em> baz_</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 445 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-445"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_445() {
        value md = "*foo __bar *baz bim__ bam*\n";
        value html = "<p><em>foo <strong>bar *baz bim</strong> bam</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 446 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-446"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_446() {
        value md = "**foo **bar baz**\n";
        value html = "<p>**foo <strong>bar baz</strong></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 447 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-447"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_447() {
        value md = "*foo *bar baz*\n";
        value html = "<p>*foo <em>bar baz</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 448 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-448"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_448() {
        value md = "*[bar*](/url)\n";
        value html = "<p>*<a href=\"/url\">bar*</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 449 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-449"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_449() {
        value md = "_foo [bar_](/url)\n";
        value html = "<p>_foo <a href=\"/url\">bar_</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 450 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-450"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_450() {
        value md = "*<img src=\"foo\" title=\"*\"/>\n";
        value html = "<p>*<img src=\"foo\" title=\"*\"/></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 451 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-451"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_451() {
        value md = "**<a href=\"**\">\n";
        value html = "<p>**<a href=\"**\"></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 452 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-452"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_452() {
        value md = "__<a href=\"__\">\n";
        value html = "<p>__<a href=\"__\"></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 453 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-453"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_453() {
        value md = "*a \`*\`*\n";
        value html = "<p><em>a <code>*</code></em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 454 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-454"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_454() {
        value md = "_a \`_\`_\n";
        value html = "<p><em>a <code>_</code></em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 455 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-455"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_455() {
        value md = "**a<http://foo.bar/?q=**>\n";
        value html = "<p>**a<a href=\"http://foo.bar/?q=**\">http://foo.bar/?q=**</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 456 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-456"""
    test
    shared void specTest_Emphasis_and_strong_emphasis_456() {
        value md = "__a<http://foo.bar/?q=__>\n";
        value html = "<p>__a<a href=\"http://foo.bar/?q=__\">http://foo.bar/?q=__</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

}
