import ceylon.test{test,assertEquals}
import ceylon.markdown.core{parse}
import ceylon.markdown.html{renderPartialHtml}
import ceylon.html{renderTemplate,Node}

/*
  The code in this file was generated by the make_tests.py script
  You might want to run it from time to time
  to keep these tests up to date with the latest
  commonmark spec tests
*/
shared class Fenced_code_blocks() {
    String render(String md) {
        value sb = StringBuilder();
        value f = sb.append;
        for (node in renderPartialHtml(parse(md))) {
            assert(is Node node);
            renderTemplate(node, f);
        }
        return sb.string;
    }

    """Test for example 88 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-88"""
    test
    shared void specTest_Fenced_code_blocks_88() {
        value md = "\`\`\`\n<\n >\n\`\`\`\n";
        value html = "<pre><code>&lt;\n &gt;\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 89 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-89"""
    test
    shared void specTest_Fenced_code_blocks_89() {
        value md = "~~~\n<\n >\n~~~\n";
        value html = "<pre><code>&lt;\n &gt;\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 90 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-90"""
    test
    shared void specTest_Fenced_code_blocks_90() {
        value md = "\`\`\`\naaa\n~~~\n\`\`\`\n";
        value html = "<pre><code>aaa\n~~~\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 91 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-91"""
    test
    shared void specTest_Fenced_code_blocks_91() {
        value md = "~~~\naaa\n\`\`\`\n~~~\n";
        value html = "<pre><code>aaa\n\`\`\`\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 92 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-92"""
    test
    shared void specTest_Fenced_code_blocks_92() {
        value md = "\`\`\`\`\naaa\n\`\`\`\n\`\`\`\`\`\`\n";
        value html = "<pre><code>aaa\n\`\`\`\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 93 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-93"""
    test
    shared void specTest_Fenced_code_blocks_93() {
        value md = "~~~~\naaa\n~~~\n~~~~\n";
        value html = "<pre><code>aaa\n~~~\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 94 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-94"""
    test
    shared void specTest_Fenced_code_blocks_94() {
        value md = "\`\`\`\n";
        value html = "<pre><code></code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 95 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-95"""
    test
    shared void specTest_Fenced_code_blocks_95() {
        value md = "\`\`\`\`\`\n\n\`\`\`\naaa\n";
        value html = "<pre><code>\n\`\`\`\naaa\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 96 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-96"""
    test
    shared void specTest_Fenced_code_blocks_96() {
        value md = "> \`\`\`\n> aaa\n\nbbb\n";
        value html = "<blockquote>\n<pre><code>aaa\n</code></pre>\n</blockquote>\n<p>bbb</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 97 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-97"""
    test
    shared void specTest_Fenced_code_blocks_97() {
        value md = "\`\`\`\n\n  \n\`\`\`\n";
        value html = "<pre><code>\n  \n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 98 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-98"""
    test
    shared void specTest_Fenced_code_blocks_98() {
        value md = "\`\`\`\n\`\`\`\n";
        value html = "<pre><code></code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 99 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-99"""
    test
    shared void specTest_Fenced_code_blocks_99() {
        value md = " \`\`\`\n aaa\naaa\n\`\`\`\n";
        value html = "<pre><code>aaa\naaa\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 100 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-100"""
    test
    shared void specTest_Fenced_code_blocks_100() {
        value md = "  \`\`\`\naaa\n  aaa\naaa\n  \`\`\`\n";
        value html = "<pre><code>aaa\naaa\naaa\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 101 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-101"""
    test
    shared void specTest_Fenced_code_blocks_101() {
        value md = "   \`\`\`\n   aaa\n    aaa\n  aaa\n   \`\`\`\n";
        value html = "<pre><code>aaa\n aaa\naaa\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 102 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-102"""
    test
    shared void specTest_Fenced_code_blocks_102() {
        value md = "    \`\`\`\n    aaa\n    \`\`\`\n";
        value html = "<pre><code>\`\`\`\naaa\n\`\`\`\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 103 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-103"""
    test
    shared void specTest_Fenced_code_blocks_103() {
        value md = "\`\`\`\naaa\n  \`\`\`\n";
        value html = "<pre><code>aaa\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 104 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-104"""
    test
    shared void specTest_Fenced_code_blocks_104() {
        value md = "   \`\`\`\naaa\n  \`\`\`\n";
        value html = "<pre><code>aaa\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 105 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-105"""
    test
    shared void specTest_Fenced_code_blocks_105() {
        value md = "\`\`\`\naaa\n    \`\`\`\n";
        value html = "<pre><code>aaa\n    \`\`\`\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 106 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-106"""
    test
    shared void specTest_Fenced_code_blocks_106() {
        value md = "\`\`\` \`\`\`\naaa\n";
        value html = "<p><code></code>\naaa</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 107 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-107"""
    test
    shared void specTest_Fenced_code_blocks_107() {
        value md = "~~~~~~\naaa\n~~~ ~~\n";
        value html = "<pre><code>aaa\n~~~ ~~\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 108 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-108"""
    test
    shared void specTest_Fenced_code_blocks_108() {
        value md = "foo\n\`\`\`\nbar\n\`\`\`\nbaz\n";
        value html = "<p>foo</p>\n<pre><code>bar\n</code></pre>\n<p>baz</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 109 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-109"""
    test
    shared void specTest_Fenced_code_blocks_109() {
        value md = "foo\n---\n~~~\nbar\n~~~\n# baz\n";
        value html = "<h2>foo</h2>\n<pre><code>bar\n</code></pre>\n<h1>baz</h1>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 110 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-110"""
    test
    shared void specTest_Fenced_code_blocks_110() {
        value md = "\`\`\`ruby\ndef foo(x)\n  return 3\nend\n\`\`\`\n";
        value html = "<pre><code class=\"language-ruby\">def foo(x)\n  return 3\nend\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 111 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-111"""
    test
    shared void specTest_Fenced_code_blocks_111() {
        value md = "~~~~    ruby startline=3 $%@#$\ndef foo(x)\n  return 3\nend\n~~~~~~~\n";
        value html = "<pre><code class=\"language-ruby\">def foo(x)\n  return 3\nend\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 112 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-112"""
    test
    shared void specTest_Fenced_code_blocks_112() {
        value md = "\`\`\`\`;\n\`\`\`\`\n";
        value html = "<pre><code class=\"language-;\"></code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 113 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-113"""
    test
    shared void specTest_Fenced_code_blocks_113() {
        value md = "\`\`\` aa \`\`\`\nfoo\n";
        value html = "<p><code>aa</code>\nfoo</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 114 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-114"""
    test
    shared void specTest_Fenced_code_blocks_114() {
        value md = "\`\`\`\n\`\`\` aaa\n\`\`\`\n";
        value html = "<pre><code>\`\`\` aaa\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

}
