import ceylon.test{test,assertEquals}
import ceylon.markdown.core{parse}
import ceylon.markdown.html{renderPartialHtml}
import ceylon.html{renderTemplate,Node}

/*
  The code in this file was generated by the make_tests.py script
  You might want to run it from time to time
  to keep these tests up to date with the latest
  commonmark spec tests
*/
shared class HTML_blocks() {
    String render(String md) {
        value sb = StringBuilder();
        value f = sb.append;
        for (node in renderPartialHtml(parse(md))) {
            assert(is Node node);
            renderTemplate(node, f);
        }
        return sb.string;
    }

    """Test for example 115 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-115"""
    test
    shared void specTest_HTML_blocks_115() {
        value md = "<table>\n  <tr>\n    <td>\n           hi\n    </td>\n  </tr>\n</table>\n\nokay.\n";
        value html = "<table>\n  <tr>\n    <td>\n           hi\n    </td>\n  </tr>\n</table>\n<p>okay.</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 116 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-116"""
    test
    shared void specTest_HTML_blocks_116() {
        value md = " <div>\n  *hello*\n         <foo><a>\n";
        value html = " <div>\n  *hello*\n         <foo><a>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 117 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-117"""
    test
    shared void specTest_HTML_blocks_117() {
        value md = "</div>\n*foo*\n";
        value html = "</div>\n*foo*\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 118 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-118"""
    test
    shared void specTest_HTML_blocks_118() {
        value md = "<DIV CLASS=\"foo\">\n\n*Markdown*\n\n</DIV>\n";
        value html = "<DIV CLASS=\"foo\">\n<p><em>Markdown</em></p>\n</DIV>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 119 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-119"""
    test
    shared void specTest_HTML_blocks_119() {
        value md = "<div id=\"foo\"\n  class=\"bar\">\n</div>\n";
        value html = "<div id=\"foo\"\n  class=\"bar\">\n</div>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 120 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-120"""
    test
    shared void specTest_HTML_blocks_120() {
        value md = "<div id=\"foo\" class=\"bar\n  baz\">\n</div>\n";
        value html = "<div id=\"foo\" class=\"bar\n  baz\">\n</div>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 121 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-121"""
    test
    shared void specTest_HTML_blocks_121() {
        value md = "<div>\n*foo*\n\n*bar*\n";
        value html = "<div>\n*foo*\n<p><em>bar</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 122 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-122"""
    test
    shared void specTest_HTML_blocks_122() {
        value md = "<div id=\"foo\"\n*hi*\n";
        value html = "<div id=\"foo\"\n*hi*\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 123 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-123"""
    test
    shared void specTest_HTML_blocks_123() {
        value md = "<div class\nfoo\n";
        value html = "<div class\nfoo\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 124 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-124"""
    test
    shared void specTest_HTML_blocks_124() {
        value md = "<div *???-&&&-<---\n*foo*\n";
        value html = "<div *???-&&&-<---\n*foo*\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 125 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-125"""
    test
    shared void specTest_HTML_blocks_125() {
        value md = "<div><a href=\"bar\">*foo*</a></div>\n";
        value html = "<div><a href=\"bar\">*foo*</a></div>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 126 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-126"""
    test
    shared void specTest_HTML_blocks_126() {
        value md = "<table><tr><td>\nfoo\n</td></tr></table>\n";
        value html = "<table><tr><td>\nfoo\n</td></tr></table>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 127 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-127"""
    test
    shared void specTest_HTML_blocks_127() {
        value md = "<div></div>\n\`\`\` c\nint x = 33;\n\`\`\`\n";
        value html = "<div></div>\n\`\`\` c\nint x = 33;\n\`\`\`\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 128 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-128"""
    test
    shared void specTest_HTML_blocks_128() {
        value md = "<a href=\"foo\">\n*bar*\n</a>\n";
        value html = "<a href=\"foo\">\n*bar*\n</a>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 129 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-129"""
    test
    shared void specTest_HTML_blocks_129() {
        value md = "<Warning>\n*bar*\n</Warning>\n";
        value html = "<Warning>\n*bar*\n</Warning>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 130 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-130"""
    test
    shared void specTest_HTML_blocks_130() {
        value md = "<i class=\"foo\">\n*bar*\n</i>\n";
        value html = "<i class=\"foo\">\n*bar*\n</i>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 131 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-131"""
    test
    shared void specTest_HTML_blocks_131() {
        value md = "</ins>\n*bar*\n";
        value html = "</ins>\n*bar*\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 132 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-132"""
    test
    shared void specTest_HTML_blocks_132() {
        value md = "<del>\n*foo*\n</del>\n";
        value html = "<del>\n*foo*\n</del>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 133 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-133"""
    test
    shared void specTest_HTML_blocks_133() {
        value md = "<del>\n\n*foo*\n\n</del>\n";
        value html = "<del>\n<p><em>foo</em></p>\n</del>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 134 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-134"""
    test
    shared void specTest_HTML_blocks_134() {
        value md = "<del>*foo*</del>\n";
        value html = "<p><del><em>foo</em></del></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 135 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-135"""
    test
    shared void specTest_HTML_blocks_135() {
        value md = "<pre language=\"haskell\"><code>\nimport Text.HTML.TagSoup\n\nmain :: IO ()\nmain = print $ parseTags tags\n</code></pre>\nokay\n";
        value html = "<pre language=\"haskell\"><code>\nimport Text.HTML.TagSoup\n\nmain :: IO ()\nmain = print $ parseTags tags\n</code></pre>\n<p>okay</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 136 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-136"""
    test
    shared void specTest_HTML_blocks_136() {
        value md = "<script type=\"text/javascript\">\n// JavaScript example\n\ndocument.getElementById(\"demo\").innerHTML = \"Hello JavaScript!\";\n</script>\nokay\n";
        value html = "<script type=\"text/javascript\">\n// JavaScript example\n\ndocument.getElementById(\"demo\").innerHTML = \"Hello JavaScript!\";\n</script>\n<p>okay</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 137 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-137"""
    test
    shared void specTest_HTML_blocks_137() {
        value md = "<style\n  type=\"text/css\">\nh1 {color:red;}\n\np {color:blue;}\n</style>\nokay\n";
        value html = "<style\n  type=\"text/css\">\nh1 {color:red;}\n\np {color:blue;}\n</style>\n<p>okay</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 138 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-138"""
    test
    shared void specTest_HTML_blocks_138() {
        value md = "<style\n  type=\"text/css\">\n\nfoo\n";
        value html = "<style\n  type=\"text/css\">\n\nfoo\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 139 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-139"""
    test
    shared void specTest_HTML_blocks_139() {
        value md = "> <div>\n> foo\n\nbar\n";
        value html = "<blockquote>\n<div>\nfoo\n</blockquote>\n<p>bar</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 140 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-140"""
    test
    shared void specTest_HTML_blocks_140() {
        value md = "- <div>\n- foo\n";
        value html = "<ul>\n<li>\n<div>\n</li>\n<li>foo</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 141 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-141"""
    test
    shared void specTest_HTML_blocks_141() {
        value md = "<style>p{color:red;}</style>\n*foo*\n";
        value html = "<style>p{color:red;}</style>\n<p><em>foo</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 142 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-142"""
    test
    shared void specTest_HTML_blocks_142() {
        value md = "<!-- foo -->*bar*\n*baz*\n";
        value html = "<!-- foo -->*bar*\n<p><em>baz</em></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 143 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-143"""
    test
    shared void specTest_HTML_blocks_143() {
        value md = "<script>\nfoo\n</script>1. *bar*\n";
        value html = "<script>\nfoo\n</script>1. *bar*\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 144 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-144"""
    test
    shared void specTest_HTML_blocks_144() {
        value md = "<!-- Foo\n\nbar\n   baz -->\nokay\n";
        value html = "<!-- Foo\n\nbar\n   baz -->\n<p>okay</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 145 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-145"""
    test
    shared void specTest_HTML_blocks_145() {
        value md = "<?php\n\n  echo '>';\n\n?>\nokay\n";
        value html = "<?php\n\n  echo '>';\n\n?>\n<p>okay</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 146 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-146"""
    test
    shared void specTest_HTML_blocks_146() {
        value md = "<!DOCTYPE html>\n";
        value html = "<!DOCTYPE html>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 147 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-147"""
    test
    shared void specTest_HTML_blocks_147() {
        value md = "<![CDATA[\nfunction matchwo(a,b)\n{\n  if (a < b && a < 0) then {\n    return 1;\n\n  } else {\n\n    return 0;\n  }\n}\n]]>\nokay\n";
        value html = "<![CDATA[\nfunction matchwo(a,b)\n{\n  if (a < b && a < 0) then {\n    return 1;\n\n  } else {\n\n    return 0;\n  }\n}\n]]>\n<p>okay</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 148 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-148"""
    test
    shared void specTest_HTML_blocks_148() {
        value md = "  <!-- foo -->\n\n    <!-- foo -->\n";
        value html = "  <!-- foo -->\n<pre><code>&lt;!-- foo --&gt;\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 149 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-149"""
    test
    shared void specTest_HTML_blocks_149() {
        value md = "  <div>\n\n    <div>\n";
        value html = "  <div>\n<pre><code>&lt;div&gt;\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 150 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-150"""
    test
    shared void specTest_HTML_blocks_150() {
        value md = "Foo\n<div>\nbar\n</div>\n";
        value html = "<p>Foo</p>\n<div>\nbar\n</div>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 151 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-151"""
    test
    shared void specTest_HTML_blocks_151() {
        value md = "<div>\nbar\n</div>\n*foo*\n";
        value html = "<div>\nbar\n</div>\n*foo*\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 152 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-152"""
    test
    shared void specTest_HTML_blocks_152() {
        value md = "Foo\n<a href=\"bar\">\nbaz\n";
        value html = "<p>Foo\n<a href=\"bar\">\nbaz</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 153 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-153"""
    test
    shared void specTest_HTML_blocks_153() {
        value md = "<div>\n\n*Emphasized* text.\n\n</div>\n";
        value html = "<div>\n<p><em>Emphasized</em> text.</p>\n</div>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 154 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-154"""
    test
    shared void specTest_HTML_blocks_154() {
        value md = "<div>\n*Emphasized* text.\n</div>\n";
        value html = "<div>\n*Emphasized* text.\n</div>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 155 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-155"""
    test
    shared void specTest_HTML_blocks_155() {
        value md = "<table>\n\n<tr>\n\n<td>\nHi\n</td>\n\n</tr>\n\n</table>\n";
        value html = "<table>\n<tr>\n<td>\nHi\n</td>\n</tr>\n</table>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 156 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-156"""
    test
    shared void specTest_HTML_blocks_156() {
        value md = "<table>\n\n  <tr>\n\n    <td>\n      Hi\n    </td>\n\n  </tr>\n\n</table>\n";
        value html = "<table>\n  <tr>\n<pre><code>&lt;td&gt;\n  Hi\n&lt;/td&gt;\n</code></pre>\n  </tr>\n</table>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

}
