import ceylon.test{test,assertEquals}
import ceylon.markdown.core{parse}
import ceylon.markdown.html{renderPartialHtml}
import ceylon.html{renderTemplate,Node}

/*
  The code in this file was generated by the make_tests.py script
  You might want to run it from time to time
  to keep these tests up to date with the latest
  commonmark spec tests
*/
shared class Images() {
    String render(String md) {
        value sb = StringBuilder();
        value f = sb.append;
        for (node in renderPartialHtml(parse(md))) {
            assert(is Node node);
            renderTemplate(node, f);
        }
        return sb.string;
    }

    """Test for example 538 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-538"""
    test
    shared void specTest_Images_538() {
        value md = "![foo](/url \"title\")\n";
        value html = "<p><img src=\"/url\" alt=\"foo\" title=\"title\" /></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 539 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-539"""
    test
    shared void specTest_Images_539() {
        value md = "![foo *bar*]\n\n[foo *bar*]: train.jpg \"train & tracks\"\n";
        value html = "<p><img src=\"train.jpg\" alt=\"foo bar\" title=\"train &amp; tracks\" /></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 540 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-540"""
    test
    shared void specTest_Images_540() {
        value md = "![foo ![bar](/url)](/url2)\n";
        value html = "<p><img src=\"/url2\" alt=\"foo bar\" /></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 541 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-541"""
    test
    shared void specTest_Images_541() {
        value md = "![foo [bar](/url)](/url2)\n";
        value html = "<p><img src=\"/url2\" alt=\"foo bar\" /></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 542 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-542"""
    test
    shared void specTest_Images_542() {
        value md = "![foo *bar*][]\n\n[foo *bar*]: train.jpg \"train & tracks\"\n";
        value html = "<p><img src=\"train.jpg\" alt=\"foo bar\" title=\"train &amp; tracks\" /></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 543 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-543"""
    test
    shared void specTest_Images_543() {
        value md = "![foo *bar*][foobar]\n\n[FOOBAR]: train.jpg \"train & tracks\"\n";
        value html = "<p><img src=\"train.jpg\" alt=\"foo bar\" title=\"train &amp; tracks\" /></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 544 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-544"""
    test
    shared void specTest_Images_544() {
        value md = "![foo](train.jpg)\n";
        value html = "<p><img src=\"train.jpg\" alt=\"foo\" /></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 545 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-545"""
    test
    shared void specTest_Images_545() {
        value md = "My ![foo bar](/path/to/train.jpg  \"title\"   )\n";
        value html = "<p>My <img src=\"/path/to/train.jpg\" alt=\"foo bar\" title=\"title\" /></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 546 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-546"""
    test
    shared void specTest_Images_546() {
        value md = "![foo](<url>)\n";
        value html = "<p><img src=\"url\" alt=\"foo\" /></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 547 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-547"""
    test
    shared void specTest_Images_547() {
        value md = "![](/url)\n";
        value html = "<p><img src=\"/url\" alt=\"\" /></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 548 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-548"""
    test
    shared void specTest_Images_548() {
        value md = "![foo][bar]\n\n[bar]: /url\n";
        value html = "<p><img src=\"/url\" alt=\"foo\" /></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 549 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-549"""
    test
    shared void specTest_Images_549() {
        value md = "![foo][bar]\n\n[BAR]: /url\n";
        value html = "<p><img src=\"/url\" alt=\"foo\" /></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 550 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-550"""
    test
    shared void specTest_Images_550() {
        value md = "![foo][]\n\n[foo]: /url \"title\"\n";
        value html = "<p><img src=\"/url\" alt=\"foo\" title=\"title\" /></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 551 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-551"""
    test
    shared void specTest_Images_551() {
        value md = "![*foo* bar][]\n\n[*foo* bar]: /url \"title\"\n";
        value html = "<p><img src=\"/url\" alt=\"foo bar\" title=\"title\" /></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 552 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-552"""
    test
    shared void specTest_Images_552() {
        value md = "![Foo][]\n\n[foo]: /url \"title\"\n";
        value html = "<p><img src=\"/url\" alt=\"Foo\" title=\"title\" /></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 553 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-553"""
    test
    shared void specTest_Images_553() {
        value md = "![foo] \n[]\n\n[foo]: /url \"title\"\n";
        value html = "<p><img src=\"/url\" alt=\"foo\" title=\"title\" />\n[]</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 554 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-554"""
    test
    shared void specTest_Images_554() {
        value md = "![foo]\n\n[foo]: /url \"title\"\n";
        value html = "<p><img src=\"/url\" alt=\"foo\" title=\"title\" /></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 555 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-555"""
    test
    shared void specTest_Images_555() {
        value md = "![*foo* bar]\n\n[*foo* bar]: /url \"title\"\n";
        value html = "<p><img src=\"/url\" alt=\"foo bar\" title=\"title\" /></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 556 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-556"""
    test
    shared void specTest_Images_556() {
        value md = "![[foo]]\n\n[[foo]]: /url \"title\"\n";
        value html = "<p>![[foo]]</p>\n<p>[[foo]]: /url &quot;title&quot;</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 557 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-557"""
    test
    shared void specTest_Images_557() {
        value md = "![Foo]\n\n[foo]: /url \"title\"\n";
        value html = "<p><img src=\"/url\" alt=\"Foo\" title=\"title\" /></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 558 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-558"""
    test
    shared void specTest_Images_558() {
        value md = "\\!\\[foo]\n\n[foo]: /url \"title\"\n";
        value html = "<p>![foo]</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 559 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-559"""
    test
    shared void specTest_Images_559() {
        value md = "\\![foo]\n\n[foo]: /url \"title\"\n";
        value html = "<p>!<a href=\"/url\" title=\"title\">foo</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

}
