import ceylon.test{test,assertEquals}
import ceylon.markdown.core{parse}
import ceylon.markdown.html{renderPartialHtml}
import ceylon.html{renderTemplate,Node}

/*
  The code in this file was generated by the make_tests.py script
  You might want to run it from time to time
  to keep these tests up to date with the latest
  commonmark spec tests
*/
shared class Link_reference_definitions() {
    String render(String md) {
        value sb = StringBuilder();
        value f = sb.append;
        for (node in renderPartialHtml(parse(md))) {
            assert(is Node node);
            renderTemplate(node, f);
        }
        return sb.string;
    }

    """Test for example 157 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-157"""
    test
    shared void specTest_Link_reference_definitions_157() {
        value md = "[foo]: /url \"title\"\n\n[foo]\n";
        value html = "<p><a href=\"/url\" title=\"title\">foo</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 158 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-158"""
    test
    shared void specTest_Link_reference_definitions_158() {
        value md = "   [foo]: \n      /url  \n           'the title'  \n\n[foo]\n";
        value html = "<p><a href=\"/url\" title=\"the title\">foo</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 159 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-159"""
    test
    shared void specTest_Link_reference_definitions_159() {
        value md = "[Foo*bar\\]]:my_(url) 'title (with parens)'\n\n[Foo*bar\\]]\n";
        value html = "<p><a href=\"my_(url)\" title=\"title (with parens)\">Foo*bar]</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 160 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-160"""
    test
    shared void specTest_Link_reference_definitions_160() {
        value md = "[Foo bar]:\n<my%20url>\n'title'\n\n[Foo bar]\n";
        value html = "<p><a href=\"my%20url\" title=\"title\">Foo bar</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 161 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-161"""
    test
    shared void specTest_Link_reference_definitions_161() {
        value md = "[foo]: /url '\ntitle\nline1\nline2\n'\n\n[foo]\n";
        value html = "<p><a href=\"/url\" title=\"\ntitle\nline1\nline2\n\">foo</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 162 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-162"""
    test
    shared void specTest_Link_reference_definitions_162() {
        value md = "[foo]: /url 'title\n\nwith blank line'\n\n[foo]\n";
        value html = "<p>[foo]: /url 'title</p>\n<p>with blank line'</p>\n<p>[foo]</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 163 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-163"""
    test
    shared void specTest_Link_reference_definitions_163() {
        value md = "[foo]:\n/url\n\n[foo]\n";
        value html = "<p><a href=\"/url\">foo</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 164 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-164"""
    test
    shared void specTest_Link_reference_definitions_164() {
        value md = "[foo]:\n\n[foo]\n";
        value html = "<p>[foo]:</p>\n<p>[foo]</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 165 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-165"""
    test
    shared void specTest_Link_reference_definitions_165() {
        value md = "[foo]: /url\\bar\\*baz \"foo\\\"bar\\baz\"\n\n[foo]\n";
        value html = "<p><a href=\"/url%5Cbar*baz\" title=\"foo&quot;bar\\baz\">foo</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 166 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-166"""
    test
    shared void specTest_Link_reference_definitions_166() {
        value md = "[foo]\n\n[foo]: url\n";
        value html = "<p><a href=\"url\">foo</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 167 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-167"""
    test
    shared void specTest_Link_reference_definitions_167() {
        value md = "[foo]\n\n[foo]: first\n[foo]: second\n";
        value html = "<p><a href=\"first\">foo</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 168 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-168"""
    test
    shared void specTest_Link_reference_definitions_168() {
        value md = "[FOO]: /url\n\n[Foo]\n";
        value html = "<p><a href=\"/url\">Foo</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 169 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-169"""
    test
    shared void specTest_Link_reference_definitions_169() {
        value md = "[ΑΓΩ]: /φου\n\n[αγω]\n";
        value html = "<p><a href=\"/%CF%86%CE%BF%CF%85\">αγω</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 170 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-170"""
    test
    shared void specTest_Link_reference_definitions_170() {
        value md = "[foo]: /url\n";
        value html = "";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 171 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-171"""
    test
    shared void specTest_Link_reference_definitions_171() {
        value md = "[\nfoo\n]: /url\nbar\n";
        value html = "<p>bar</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 172 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-172"""
    test
    shared void specTest_Link_reference_definitions_172() {
        value md = "[foo]: /url \"title\" ok\n";
        value html = "<p>[foo]: /url &quot;title&quot; ok</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 173 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-173"""
    test
    shared void specTest_Link_reference_definitions_173() {
        value md = "[foo]: /url\n\"title\" ok\n";
        value html = "<p>&quot;title&quot; ok</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 174 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-174"""
    test
    shared void specTest_Link_reference_definitions_174() {
        value md = "    [foo]: /url \"title\"\n\n[foo]\n";
        value html = "<pre><code>[foo]: /url &quot;title&quot;\n</code></pre>\n<p>[foo]</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 175 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-175"""
    test
    shared void specTest_Link_reference_definitions_175() {
        value md = "\`\`\`\n[foo]: /url\n\`\`\`\n\n[foo]\n";
        value html = "<pre><code>[foo]: /url\n</code></pre>\n<p>[foo]</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 176 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-176"""
    test
    shared void specTest_Link_reference_definitions_176() {
        value md = "Foo\n[bar]: /baz\n\n[bar]\n";
        value html = "<p>Foo\n[bar]: /baz</p>\n<p>[bar]</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 177 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-177"""
    test
    shared void specTest_Link_reference_definitions_177() {
        value md = "# [Foo]\n[foo]: /url\n> bar\n";
        value html = "<h1><a href=\"/url\">Foo</a></h1>\n<blockquote>\n<p>bar</p>\n</blockquote>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 178 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-178"""
    test
    shared void specTest_Link_reference_definitions_178() {
        value md = "[foo]: /foo-url \"foo\"\n[bar]: /bar-url\n  \"bar\"\n[baz]: /baz-url\n\n[foo],\n[bar],\n[baz]\n";
        value html = "<p><a href=\"/foo-url\" title=\"foo\">foo</a>,\n<a href=\"/bar-url\" title=\"bar\">bar</a>,\n<a href=\"/baz-url\">baz</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 179 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-179"""
    test
    shared void specTest_Link_reference_definitions_179() {
        value md = "[foo]\n\n> [foo]: /url\n";
        value html = "<p><a href=\"/url\">foo</a></p>\n<blockquote>\n</blockquote>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

}
