import ceylon.test{test,assertEquals}
import ceylon.markdown.core{parse}
import ceylon.markdown.html{renderPartialHtml}
import ceylon.html{renderTemplate,Node}

/*
  The code in this file was generated by the make_tests.py script
  You might want to run it from time to time
  to keep these tests up to date with the latest
  commonmark spec tests
*/
shared class Links() {
    String render(String md) {
        value sb = StringBuilder();
        value f = sb.append;
        for (node in renderPartialHtml(parse(md))) {
            assert(is Node node);
            renderTemplate(node, f);
        }
        return sb.string;
    }

    """Test for example 457 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-457"""
    test
    shared void specTest_Links_457() {
        value md = "[link](/uri \"title\")\n";
        value html = "<p><a href=\"/uri\" title=\"title\">link</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 458 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-458"""
    test
    shared void specTest_Links_458() {
        value md = "[link](/uri)\n";
        value html = "<p><a href=\"/uri\">link</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 459 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-459"""
    test
    shared void specTest_Links_459() {
        value md = "[link]()\n";
        value html = "<p><a href=\"\">link</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 460 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-460"""
    test
    shared void specTest_Links_460() {
        value md = "[link](<>)\n";
        value html = "<p><a href=\"\">link</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 461 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-461"""
    test
    shared void specTest_Links_461() {
        value md = "[link](/my uri)\n";
        value html = "<p>[link](/my uri)</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 462 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-462"""
    test
    shared void specTest_Links_462() {
        value md = "[link](</my uri>)\n";
        value html = "<p>[link](&lt;/my uri&gt;)</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 463 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-463"""
    test
    shared void specTest_Links_463() {
        value md = "[link](foo\nbar)\n";
        value html = "<p>[link](foo\nbar)</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 464 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-464"""
    test
    shared void specTest_Links_464() {
        value md = "[link](<foo\nbar>)\n";
        value html = "<p>[link](<foo\nbar>)</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 465 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-465"""
    test
    shared void specTest_Links_465() {
        value md = "[link](\\(foo\\))\n";
        value html = "<p><a href=\"(foo)\">link</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 466 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-466"""
    test
    shared void specTest_Links_466() {
        value md = "[link]((foo)and(bar))\n";
        value html = "<p><a href=\"(foo)and(bar)\">link</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 467 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-467"""
    test
    shared void specTest_Links_467() {
        value md = "[link](foo(and(bar)))\n";
        value html = "<p>[link](foo(and(bar)))</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 468 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-468"""
    test
    shared void specTest_Links_468() {
        value md = "[link](foo(and\\(bar\\)))\n";
        value html = "<p><a href=\"foo(and(bar))\">link</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 469 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-469"""
    test
    shared void specTest_Links_469() {
        value md = "[link](<foo(and(bar))>)\n";
        value html = "<p><a href=\"foo(and(bar))\">link</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 470 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-470"""
    test
    shared void specTest_Links_470() {
        value md = "[link](foo\\)\\:)\n";
        value html = "<p><a href=\"foo):\">link</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 471 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-471"""
    test
    shared void specTest_Links_471() {
        value md = "[link](#fragment)\n\n[link](http://example.com#fragment)\n\n[link](http://example.com?foo=3#frag)\n";
        value html = "<p><a href=\"#fragment\">link</a></p>\n<p><a href=\"http://example.com#fragment\">link</a></p>\n<p><a href=\"http://example.com?foo=3#frag\">link</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 472 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-472"""
    test
    shared void specTest_Links_472() {
        value md = "[link](foo\\bar)\n";
        value html = "<p><a href=\"foo%5Cbar\">link</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 473 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-473"""
    test
    shared void specTest_Links_473() {
        value md = "[link](foo%20b&auml;)\n";
        value html = "<p><a href=\"foo%20b%C3%A4\">link</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 474 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-474"""
    test
    shared void specTest_Links_474() {
        value md = "[link](\"title\")\n";
        value html = "<p><a href=\"%22title%22\">link</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 475 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-475"""
    test
    shared void specTest_Links_475() {
        value md = "[link](/url \"title\")\n[link](/url 'title')\n[link](/url (title))\n";
        value html = "<p><a href=\"/url\" title=\"title\">link</a>\n<a href=\"/url\" title=\"title\">link</a>\n<a href=\"/url\" title=\"title\">link</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 476 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-476"""
    test
    shared void specTest_Links_476() {
        value md = "[link](/url \"title \\\"&quot;\")\n";
        value html = "<p><a href=\"/url\" title=\"title &quot;&quot;\">link</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 477 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-477"""
    test
    shared void specTest_Links_477() {
        value md = "[link](/url \"title \"and\" title\")\n";
        value html = "<p>[link](/url &quot;title &quot;and&quot; title&quot;)</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 478 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-478"""
    test
    shared void specTest_Links_478() {
        value md = "[link](/url 'title \"and\" title')\n";
        value html = "<p><a href=\"/url\" title=\"title &quot;and&quot; title\">link</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 479 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-479"""
    test
    shared void specTest_Links_479() {
        value md = "[link](   /uri\n  \"title\"  )\n";
        value html = "<p><a href=\"/uri\" title=\"title\">link</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 480 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-480"""
    test
    shared void specTest_Links_480() {
        value md = "[link] (/uri)\n";
        value html = "<p>[link] (/uri)</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 481 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-481"""
    test
    shared void specTest_Links_481() {
        value md = "[link [foo [bar]]](/uri)\n";
        value html = "<p><a href=\"/uri\">link [foo [bar]]</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 482 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-482"""
    test
    shared void specTest_Links_482() {
        value md = "[link] bar](/uri)\n";
        value html = "<p>[link] bar](/uri)</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 483 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-483"""
    test
    shared void specTest_Links_483() {
        value md = "[link [bar](/uri)\n";
        value html = "<p>[link <a href=\"/uri\">bar</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 484 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-484"""
    test
    shared void specTest_Links_484() {
        value md = "[link \\[bar](/uri)\n";
        value html = "<p><a href=\"/uri\">link [bar</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 485 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-485"""
    test
    shared void specTest_Links_485() {
        value md = "[link *foo **bar** \`#\`*](/uri)\n";
        value html = "<p><a href=\"/uri\">link <em>foo <strong>bar</strong> <code>#</code></em></a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 486 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-486"""
    test
    shared void specTest_Links_486() {
        value md = "[![moon](moon.jpg)](/uri)\n";
        value html = "<p><a href=\"/uri\"><img src=\"moon.jpg\" alt=\"moon\" /></a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 487 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-487"""
    test
    shared void specTest_Links_487() {
        value md = "[foo [bar](/uri)](/uri)\n";
        value html = "<p>[foo <a href=\"/uri\">bar</a>](/uri)</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 488 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-488"""
    test
    shared void specTest_Links_488() {
        value md = "[foo *[bar [baz](/uri)](/uri)*](/uri)\n";
        value html = "<p>[foo <em>[bar <a href=\"/uri\">baz</a>](/uri)</em>](/uri)</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 489 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-489"""
    test
    shared void specTest_Links_489() {
        value md = "![[[foo](uri1)](uri2)](uri3)\n";
        value html = "<p><img src=\"uri3\" alt=\"[foo](uri2)\" /></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 490 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-490"""
    test
    shared void specTest_Links_490() {
        value md = "*[foo*](/uri)\n";
        value html = "<p>*<a href=\"/uri\">foo*</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 491 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-491"""
    test
    shared void specTest_Links_491() {
        value md = "[foo *bar](baz*)\n";
        value html = "<p><a href=\"baz*\">foo *bar</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 492 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-492"""
    test
    shared void specTest_Links_492() {
        value md = "*foo [bar* baz]\n";
        value html = "<p><em>foo [bar</em> baz]</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 493 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-493"""
    test
    shared void specTest_Links_493() {
        value md = "[foo <bar attr=\"](baz)\">\n";
        value html = "<p>[foo <bar attr=\"](baz)\"></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 494 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-494"""
    test
    shared void specTest_Links_494() {
        value md = "[foo\`](/uri)\`\n";
        value html = "<p>[foo<code>](/uri)</code></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 495 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-495"""
    test
    shared void specTest_Links_495() {
        value md = "[foo<http://example.com/?search=](uri)>\n";
        value html = "<p>[foo<a href=\"http://example.com/?search=%5D(uri)\">http://example.com/?search=](uri)</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 496 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-496"""
    test
    shared void specTest_Links_496() {
        value md = "[foo][bar]\n\n[bar]: /url \"title\"\n";
        value html = "<p><a href=\"/url\" title=\"title\">foo</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 497 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-497"""
    test
    shared void specTest_Links_497() {
        value md = "[link [foo [bar]]][ref]\n\n[ref]: /uri\n";
        value html = "<p><a href=\"/uri\">link [foo [bar]]</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 498 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-498"""
    test
    shared void specTest_Links_498() {
        value md = "[link \\[bar][ref]\n\n[ref]: /uri\n";
        value html = "<p><a href=\"/uri\">link [bar</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 499 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-499"""
    test
    shared void specTest_Links_499() {
        value md = "[link *foo **bar** \`#\`*][ref]\n\n[ref]: /uri\n";
        value html = "<p><a href=\"/uri\">link <em>foo <strong>bar</strong> <code>#</code></em></a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 500 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-500"""
    test
    shared void specTest_Links_500() {
        value md = "[![moon](moon.jpg)][ref]\n\n[ref]: /uri\n";
        value html = "<p><a href=\"/uri\"><img src=\"moon.jpg\" alt=\"moon\" /></a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 501 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-501"""
    test
    shared void specTest_Links_501() {
        value md = "[foo [bar](/uri)][ref]\n\n[ref]: /uri\n";
        value html = "<p>[foo <a href=\"/uri\">bar</a>]<a href=\"/uri\">ref</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 502 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-502"""
    test
    shared void specTest_Links_502() {
        value md = "[foo *bar [baz][ref]*][ref]\n\n[ref]: /uri\n";
        value html = "<p>[foo <em>bar <a href=\"/uri\">baz</a></em>]<a href=\"/uri\">ref</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 503 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-503"""
    test
    shared void specTest_Links_503() {
        value md = "*[foo*][ref]\n\n[ref]: /uri\n";
        value html = "<p>*<a href=\"/uri\">foo*</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 504 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-504"""
    test
    shared void specTest_Links_504() {
        value md = "[foo *bar][ref]\n\n[ref]: /uri\n";
        value html = "<p><a href=\"/uri\">foo *bar</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 505 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-505"""
    test
    shared void specTest_Links_505() {
        value md = "[foo <bar attr=\"][ref]\">\n\n[ref]: /uri\n";
        value html = "<p>[foo <bar attr=\"][ref]\"></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 506 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-506"""
    test
    shared void specTest_Links_506() {
        value md = "[foo\`][ref]\`\n\n[ref]: /uri\n";
        value html = "<p>[foo<code>][ref]</code></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 507 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-507"""
    test
    shared void specTest_Links_507() {
        value md = "[foo<http://example.com/?search=][ref]>\n\n[ref]: /uri\n";
        value html = "<p>[foo<a href=\"http://example.com/?search=%5D%5Bref%5D\">http://example.com/?search=][ref]</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 508 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-508"""
    test
    shared void specTest_Links_508() {
        value md = "[foo][BaR]\n\n[bar]: /url \"title\"\n";
        value html = "<p><a href=\"/url\" title=\"title\">foo</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 509 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-509"""
    test
    shared void specTest_Links_509() {
        value md = "[Толпой][Толпой] is a Russian word.\n\n[ТОЛПОЙ]: /url\n";
        value html = "<p><a href=\"/url\">Толпой</a> is a Russian word.</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 510 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-510"""
    test
    shared void specTest_Links_510() {
        value md = "[Foo\n  bar]: /url\n\n[Baz][Foo bar]\n";
        value html = "<p><a href=\"/url\">Baz</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 511 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-511"""
    test
    shared void specTest_Links_511() {
        value md = "[foo] [bar]\n\n[bar]: /url \"title\"\n";
        value html = "<p>[foo] <a href=\"/url\" title=\"title\">bar</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 512 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-512"""
    test
    shared void specTest_Links_512() {
        value md = "[foo]\n[bar]\n\n[bar]: /url \"title\"\n";
        value html = "<p>[foo]\n<a href=\"/url\" title=\"title\">bar</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 513 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-513"""
    test
    shared void specTest_Links_513() {
        value md = "[foo]: /url1\n\n[foo]: /url2\n\n[bar][foo]\n";
        value html = "<p><a href=\"/url1\">bar</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 514 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-514"""
    test
    shared void specTest_Links_514() {
        value md = "[bar][foo\\!]\n\n[foo!]: /url\n";
        value html = "<p>[bar][foo!]</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 515 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-515"""
    test
    shared void specTest_Links_515() {
        value md = "[foo][ref[]\n\n[ref[]: /uri\n";
        value html = "<p>[foo][ref[]</p>\n<p>[ref[]: /uri</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 516 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-516"""
    test
    shared void specTest_Links_516() {
        value md = "[foo][ref[bar]]\n\n[ref[bar]]: /uri\n";
        value html = "<p>[foo][ref[bar]]</p>\n<p>[ref[bar]]: /uri</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 517 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-517"""
    test
    shared void specTest_Links_517() {
        value md = "[[[foo]]]\n\n[[[foo]]]: /url\n";
        value html = "<p>[[[foo]]]</p>\n<p>[[[foo]]]: /url</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 518 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-518"""
    test
    shared void specTest_Links_518() {
        value md = "[foo][ref\\[]\n\n[ref\\[]: /uri\n";
        value html = "<p><a href=\"/uri\">foo</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 519 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-519"""
    test
    shared void specTest_Links_519() {
        value md = "[bar\\\\]: /uri\n\n[bar\\\\]\n";
        value html = "<p><a href=\"/uri\">bar\\</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 520 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-520"""
    test
    shared void specTest_Links_520() {
        value md = "[]\n\n[]: /uri\n";
        value html = "<p>[]</p>\n<p>[]: /uri</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 521 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-521"""
    test
    shared void specTest_Links_521() {
        value md = "[\n ]\n\n[\n ]: /uri\n";
        value html = "<p>[\n]</p>\n<p>[\n]: /uri</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 522 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-522"""
    test
    shared void specTest_Links_522() {
        value md = "[foo][]\n\n[foo]: /url \"title\"\n";
        value html = "<p><a href=\"/url\" title=\"title\">foo</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 523 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-523"""
    test
    shared void specTest_Links_523() {
        value md = "[*foo* bar][]\n\n[*foo* bar]: /url \"title\"\n";
        value html = "<p><a href=\"/url\" title=\"title\"><em>foo</em> bar</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 524 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-524"""
    test
    shared void specTest_Links_524() {
        value md = "[Foo][]\n\n[foo]: /url \"title\"\n";
        value html = "<p><a href=\"/url\" title=\"title\">Foo</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 525 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-525"""
    test
    shared void specTest_Links_525() {
        value md = "[foo] \n[]\n\n[foo]: /url \"title\"\n";
        value html = "<p><a href=\"/url\" title=\"title\">foo</a>\n[]</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 526 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-526"""
    test
    shared void specTest_Links_526() {
        value md = "[foo]\n\n[foo]: /url \"title\"\n";
        value html = "<p><a href=\"/url\" title=\"title\">foo</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 527 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-527"""
    test
    shared void specTest_Links_527() {
        value md = "[*foo* bar]\n\n[*foo* bar]: /url \"title\"\n";
        value html = "<p><a href=\"/url\" title=\"title\"><em>foo</em> bar</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 528 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-528"""
    test
    shared void specTest_Links_528() {
        value md = "[[*foo* bar]]\n\n[*foo* bar]: /url \"title\"\n";
        value html = "<p>[<a href=\"/url\" title=\"title\"><em>foo</em> bar</a>]</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 529 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-529"""
    test
    shared void specTest_Links_529() {
        value md = "[[bar [foo]\n\n[foo]: /url\n";
        value html = "<p>[[bar <a href=\"/url\">foo</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 530 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-530"""
    test
    shared void specTest_Links_530() {
        value md = "[Foo]\n\n[foo]: /url \"title\"\n";
        value html = "<p><a href=\"/url\" title=\"title\">Foo</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 531 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-531"""
    test
    shared void specTest_Links_531() {
        value md = "[foo] bar\n\n[foo]: /url\n";
        value html = "<p><a href=\"/url\">foo</a> bar</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 532 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-532"""
    test
    shared void specTest_Links_532() {
        value md = "\\[foo]\n\n[foo]: /url \"title\"\n";
        value html = "<p>[foo]</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 533 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-533"""
    test
    shared void specTest_Links_533() {
        value md = "[foo*]: /url\n\n*[foo*]\n";
        value html = "<p>*<a href=\"/url\">foo*</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 534 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-534"""
    test
    shared void specTest_Links_534() {
        value md = "[foo][bar]\n\n[foo]: /url1\n[bar]: /url2\n";
        value html = "<p><a href=\"/url2\">foo</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 535 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-535"""
    test
    shared void specTest_Links_535() {
        value md = "[foo][bar][baz]\n\n[baz]: /url\n";
        value html = "<p>[foo]<a href=\"/url\">bar</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 536 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-536"""
    test
    shared void specTest_Links_536() {
        value md = "[foo][bar][baz]\n\n[baz]: /url1\n[bar]: /url2\n";
        value html = "<p><a href=\"/url2\">foo</a><a href=\"/url1\">baz</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 537 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-537"""
    test
    shared void specTest_Links_537() {
        value md = "[foo][bar][baz]\n\n[baz]: /url1\n[foo]: /url2\n";
        value html = "<p>[foo]<a href=\"/url1\">bar</a></p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

}
