import ceylon.test{test,assertEquals}
import ceylon.markdown.core{parse}
import ceylon.markdown.html{renderPartialHtml}
import ceylon.html{renderTemplate,Node}

/*
  The code in this file was generated by the make_tests.py script
  You might want to run it from time to time
  to keep these tests up to date with the latest
  commonmark spec tests
*/
shared class List_items() {
    String render(String md) {
        value sb = StringBuilder();
        value f = sb.append;
        for (node in renderPartialHtml(parse(md))) {
            assert(is Node node);
            renderTemplate(node, f);
        }
        return sb.string;
    }

    """Test for example 214 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-214"""
    test
    shared void specTest_List_items_214() {
        value md = "A paragraph\nwith two lines.\n\n    indented code\n\n> A block quote.\n";
        value html = "<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 215 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-215"""
    test
    shared void specTest_List_items_215() {
        value md = "1.  A paragraph\n    with two lines.\n\n        indented code\n\n    > A block quote.\n";
        value html = "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 216 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-216"""
    test
    shared void specTest_List_items_216() {
        value md = "- one\n\n two\n";
        value html = "<ul>\n<li>one</li>\n</ul>\n<p>two</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 217 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-217"""
    test
    shared void specTest_List_items_217() {
        value md = "- one\n\n  two\n";
        value html = "<ul>\n<li>\n<p>one</p>\n<p>two</p>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 218 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-218"""
    test
    shared void specTest_List_items_218() {
        value md = " -    one\n\n     two\n";
        value html = "<ul>\n<li>one</li>\n</ul>\n<pre><code> two\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 219 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-219"""
    test
    shared void specTest_List_items_219() {
        value md = " -    one\n\n      two\n";
        value html = "<ul>\n<li>\n<p>one</p>\n<p>two</p>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 220 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-220"""
    test
    shared void specTest_List_items_220() {
        value md = "   > > 1.  one\n>>\n>>     two\n";
        value html = "<blockquote>\n<blockquote>\n<ol>\n<li>\n<p>one</p>\n<p>two</p>\n</li>\n</ol>\n</blockquote>\n</blockquote>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 221 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-221"""
    test
    shared void specTest_List_items_221() {
        value md = ">>- one\n>>\n  >  > two\n";
        value html = "<blockquote>\n<blockquote>\n<ul>\n<li>one</li>\n</ul>\n<p>two</p>\n</blockquote>\n</blockquote>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 222 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-222"""
    test
    shared void specTest_List_items_222() {
        value md = "-one\n\n2.two\n";
        value html = "<p>-one</p>\n<p>2.two</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 223 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-223"""
    test
    shared void specTest_List_items_223() {
        value md = "- foo\n\n\n  bar\n";
        value html = "<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 224 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-224"""
    test
    shared void specTest_List_items_224() {
        value md = "1.  foo\n\n    \`\`\`\n    bar\n    \`\`\`\n\n    baz\n\n    > bam\n";
        value html = "<ol>\n<li>\n<p>foo</p>\n<pre><code>bar\n</code></pre>\n<p>baz</p>\n<blockquote>\n<p>bam</p>\n</blockquote>\n</li>\n</ol>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 225 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-225"""
    test
    shared void specTest_List_items_225() {
        value md = "- Foo\n\n      bar\n\n\n      baz\n";
        value html = "<ul>\n<li>\n<p>Foo</p>\n<pre><code>bar\n\n\nbaz\n</code></pre>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 226 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-226"""
    test
    shared void specTest_List_items_226() {
        value md = "123456789. ok\n";
        value html = "<ol start=\"123456789\">\n<li>ok</li>\n</ol>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 227 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-227"""
    test
    shared void specTest_List_items_227() {
        value md = "1234567890. not ok\n";
        value html = "<p>1234567890. not ok</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 228 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-228"""
    test
    shared void specTest_List_items_228() {
        value md = "0. ok\n";
        value html = "<ol start=\"0\">\n<li>ok</li>\n</ol>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 229 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-229"""
    test
    shared void specTest_List_items_229() {
        value md = "003. ok\n";
        value html = "<ol start=\"3\">\n<li>ok</li>\n</ol>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 230 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-230"""
    test
    shared void specTest_List_items_230() {
        value md = "-1. not ok\n";
        value html = "<p>-1. not ok</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 231 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-231"""
    test
    shared void specTest_List_items_231() {
        value md = "- foo\n\n      bar\n";
        value html = "<ul>\n<li>\n<p>foo</p>\n<pre><code>bar\n</code></pre>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 232 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-232"""
    test
    shared void specTest_List_items_232() {
        value md = "  10.  foo\n\n           bar\n";
        value html = "<ol start=\"10\">\n<li>\n<p>foo</p>\n<pre><code>bar\n</code></pre>\n</li>\n</ol>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 233 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-233"""
    test
    shared void specTest_List_items_233() {
        value md = "    indented code\n\nparagraph\n\n    more code\n";
        value html = "<pre><code>indented code\n</code></pre>\n<p>paragraph</p>\n<pre><code>more code\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 234 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-234"""
    test
    shared void specTest_List_items_234() {
        value md = "1.     indented code\n\n   paragraph\n\n       more code\n";
        value html = "<ol>\n<li>\n<pre><code>indented code\n</code></pre>\n<p>paragraph</p>\n<pre><code>more code\n</code></pre>\n</li>\n</ol>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 235 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-235"""
    test
    shared void specTest_List_items_235() {
        value md = "1.      indented code\n\n   paragraph\n\n       more code\n";
        value html = "<ol>\n<li>\n<pre><code> indented code\n</code></pre>\n<p>paragraph</p>\n<pre><code>more code\n</code></pre>\n</li>\n</ol>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 236 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-236"""
    test
    shared void specTest_List_items_236() {
        value md = "   foo\n\nbar\n";
        value html = "<p>foo</p>\n<p>bar</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 237 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-237"""
    test
    shared void specTest_List_items_237() {
        value md = "-    foo\n\n  bar\n";
        value html = "<ul>\n<li>foo</li>\n</ul>\n<p>bar</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 238 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-238"""
    test
    shared void specTest_List_items_238() {
        value md = "-  foo\n\n   bar\n";
        value html = "<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 239 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-239"""
    test
    shared void specTest_List_items_239() {
        value md = "-\n  foo\n-\n  \`\`\`\n  bar\n  \`\`\`\n-\n      baz\n";
        value html = "<ul>\n<li>foo</li>\n<li>\n<pre><code>bar\n</code></pre>\n</li>\n<li>\n<pre><code>baz\n</code></pre>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 240 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-240"""
    test
    shared void specTest_List_items_240() {
        value md = "-   \n  foo\n";
        value html = "<ul>\n<li>foo</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 241 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-241"""
    test
    shared void specTest_List_items_241() {
        value md = "-\n\n  foo\n";
        value html = "<ul>\n<li></li>\n</ul>\n<p>foo</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 242 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-242"""
    test
    shared void specTest_List_items_242() {
        value md = "- foo\n-\n- bar\n";
        value html = "<ul>\n<li>foo</li>\n<li></li>\n<li>bar</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 243 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-243"""
    test
    shared void specTest_List_items_243() {
        value md = "- foo\n-   \n- bar\n";
        value html = "<ul>\n<li>foo</li>\n<li></li>\n<li>bar</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 244 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-244"""
    test
    shared void specTest_List_items_244() {
        value md = "1. foo\n2.\n3. bar\n";
        value html = "<ol>\n<li>foo</li>\n<li></li>\n<li>bar</li>\n</ol>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 245 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-245"""
    test
    shared void specTest_List_items_245() {
        value md = "*\n";
        value html = "<ul>\n<li></li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 246 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-246"""
    test
    shared void specTest_List_items_246() {
        value md = "foo\n*\n\nfoo\n1.\n";
        value html = "<p>foo\n*</p>\n<p>foo\n1.</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 247 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-247"""
    test
    shared void specTest_List_items_247() {
        value md = " 1.  A paragraph\n     with two lines.\n\n         indented code\n\n     > A block quote.\n";
        value html = "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 248 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-248"""
    test
    shared void specTest_List_items_248() {
        value md = "  1.  A paragraph\n      with two lines.\n\n          indented code\n\n      > A block quote.\n";
        value html = "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 249 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-249"""
    test
    shared void specTest_List_items_249() {
        value md = "   1.  A paragraph\n       with two lines.\n\n           indented code\n\n       > A block quote.\n";
        value html = "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 250 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-250"""
    test
    shared void specTest_List_items_250() {
        value md = "    1.  A paragraph\n        with two lines.\n\n            indented code\n\n        > A block quote.\n";
        value html = "<pre><code>1.  A paragraph\n    with two lines.\n\n        indented code\n\n    &gt; A block quote.\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 251 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-251"""
    test
    shared void specTest_List_items_251() {
        value md = "  1.  A paragraph\nwith two lines.\n\n          indented code\n\n      > A block quote.\n";
        value html = "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 252 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-252"""
    test
    shared void specTest_List_items_252() {
        value md = "  1.  A paragraph\n    with two lines.\n";
        value html = "<ol>\n<li>A paragraph\nwith two lines.</li>\n</ol>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 253 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-253"""
    test
    shared void specTest_List_items_253() {
        value md = "> 1. > Blockquote\ncontinued here.\n";
        value html = "<blockquote>\n<ol>\n<li>\n<blockquote>\n<p>Blockquote\ncontinued here.</p>\n</blockquote>\n</li>\n</ol>\n</blockquote>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 254 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-254"""
    test
    shared void specTest_List_items_254() {
        value md = "> 1. > Blockquote\n> continued here.\n";
        value html = "<blockquote>\n<ol>\n<li>\n<blockquote>\n<p>Blockquote\ncontinued here.</p>\n</blockquote>\n</li>\n</ol>\n</blockquote>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 255 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-255"""
    test
    shared void specTest_List_items_255() {
        value md = "- foo\n  - bar\n    - baz\n      - boo\n";
        value html = "<ul>\n<li>foo\n<ul>\n<li>bar\n<ul>\n<li>baz\n<ul>\n<li>boo</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 256 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-256"""
    test
    shared void specTest_List_items_256() {
        value md = "- foo\n - bar\n  - baz\n   - boo\n";
        value html = "<ul>\n<li>foo</li>\n<li>bar</li>\n<li>baz</li>\n<li>boo</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 257 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-257"""
    test
    shared void specTest_List_items_257() {
        value md = "10) foo\n    - bar\n";
        value html = "<ol start=\"10\">\n<li>foo\n<ul>\n<li>bar</li>\n</ul>\n</li>\n</ol>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 258 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-258"""
    test
    shared void specTest_List_items_258() {
        value md = "10) foo\n   - bar\n";
        value html = "<ol start=\"10\">\n<li>foo</li>\n</ol>\n<ul>\n<li>bar</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 259 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-259"""
    test
    shared void specTest_List_items_259() {
        value md = "- - foo\n";
        value html = "<ul>\n<li>\n<ul>\n<li>foo</li>\n</ul>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 260 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-260"""
    test
    shared void specTest_List_items_260() {
        value md = "1. - 2. foo\n";
        value html = "<ol>\n<li>\n<ul>\n<li>\n<ol start=\"2\">\n<li>foo</li>\n</ol>\n</li>\n</ul>\n</li>\n</ol>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 261 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-261"""
    test
    shared void specTest_List_items_261() {
        value md = "- # Foo\n- Bar\n  ---\n  baz\n";
        value html = "<ul>\n<li>\n<h1>Foo</h1>\n</li>\n<li>\n<h2>Bar</h2>\nbaz</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

}
