import ceylon.test{test,assertEquals}
import ceylon.markdown.core{parse}
import ceylon.markdown.html{renderPartialHtml}
import ceylon.html{renderTemplate,Node}

/*
  The code in this file was generated by the make_tests.py script
  You might want to run it from time to time
  to keep these tests up to date with the latest
  commonmark spec tests
*/
shared class Lists() {
    String render(String md) {
        value sb = StringBuilder();
        value f = sb.append;
        for (node in renderPartialHtml(parse(md))) {
            assert(is Node node);
            renderTemplate(node, f);
        }
        return sb.string;
    }

    """Test for example 262 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-262"""
    test
    shared void specTest_Lists_262() {
        value md = "- foo\n- bar\n+ baz\n";
        value html = "<ul>\n<li>foo</li>\n<li>bar</li>\n</ul>\n<ul>\n<li>baz</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 263 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-263"""
    test
    shared void specTest_Lists_263() {
        value md = "1. foo\n2. bar\n3) baz\n";
        value html = "<ol>\n<li>foo</li>\n<li>bar</li>\n</ol>\n<ol start=\"3\">\n<li>baz</li>\n</ol>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 264 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-264"""
    test
    shared void specTest_Lists_264() {
        value md = "Foo\n- bar\n- baz\n";
        value html = "<p>Foo</p>\n<ul>\n<li>bar</li>\n<li>baz</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 265 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-265"""
    test
    shared void specTest_Lists_265() {
        value md = "";
        value html = "";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 266 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-266"""
    test
    shared void specTest_Lists_266() {
        value md = "The number of windows in my house is\n14.  The number of doors is 6.\n";
        value html = "<p>The number of windows in my house is\n14.  The number of doors is 6.</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 267 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-267"""
    test
    shared void specTest_Lists_267() {
        value md = "The number of windows in my house is\n1.  The number of doors is 6.\n";
        value html = "<p>The number of windows in my house is</p>\n<ol>\n<li>The number of doors is 6.</li>\n</ol>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 268 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-268"""
    test
    shared void specTest_Lists_268() {
        value md = "- foo\n\n- bar\n\n\n- baz\n";
        value html = "<ul>\n<li>\n<p>foo</p>\n</li>\n<li>\n<p>bar</p>\n</li>\n<li>\n<p>baz</p>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 269 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-269"""
    test
    shared void specTest_Lists_269() {
        value md = "- foo\n  - bar\n    - baz\n\n\n      bim\n";
        value html = "<ul>\n<li>foo\n<ul>\n<li>bar\n<ul>\n<li>\n<p>baz</p>\n<p>bim</p>\n</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 270 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-270"""
    test
    shared void specTest_Lists_270() {
        value md = "- foo\n- bar\n\n<!-- -->\n\n- baz\n- bim\n";
        value html = "<ul>\n<li>foo</li>\n<li>bar</li>\n</ul>\n<!-- -->\n<ul>\n<li>baz</li>\n<li>bim</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 271 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-271"""
    test
    shared void specTest_Lists_271() {
        value md = "-   foo\n\n    notcode\n\n-   foo\n\n<!-- -->\n\n    code\n";
        value html = "<ul>\n<li>\n<p>foo</p>\n<p>notcode</p>\n</li>\n<li>\n<p>foo</p>\n</li>\n</ul>\n<!-- -->\n<pre><code>code\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 272 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-272"""
    test
    shared void specTest_Lists_272() {
        value md = "- a\n - b\n  - c\n   - d\n    - e\n   - f\n  - g\n - h\n- i\n";
        value html = "<ul>\n<li>a</li>\n<li>b</li>\n<li>c</li>\n<li>d</li>\n<li>e</li>\n<li>f</li>\n<li>g</li>\n<li>h</li>\n<li>i</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 273 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-273"""
    test
    shared void specTest_Lists_273() {
        value md = "1. a\n\n  2. b\n\n    3. c\n";
        value html = "<ol>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n<li>\n<p>c</p>\n</li>\n</ol>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 274 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-274"""
    test
    shared void specTest_Lists_274() {
        value md = "- a\n- b\n\n- c\n";
        value html = "<ul>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n<li>\n<p>c</p>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 275 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-275"""
    test
    shared void specTest_Lists_275() {
        value md = "* a\n*\n\n* c\n";
        value html = "<ul>\n<li>\n<p>a</p>\n</li>\n<li></li>\n<li>\n<p>c</p>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 276 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-276"""
    test
    shared void specTest_Lists_276() {
        value md = "- a\n- b\n\n  c\n- d\n";
        value html = "<ul>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n<p>c</p>\n</li>\n<li>\n<p>d</p>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 277 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-277"""
    test
    shared void specTest_Lists_277() {
        value md = "- a\n- b\n\n  [ref]: /url\n- d\n";
        value html = "<ul>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n<li>\n<p>d</p>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 278 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-278"""
    test
    shared void specTest_Lists_278() {
        value md = "- a\n- \`\`\`\n  b\n\n\n  \`\`\`\n- c\n";
        value html = "<ul>\n<li>a</li>\n<li>\n<pre><code>b\n\n\n</code></pre>\n</li>\n<li>c</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 279 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-279"""
    test
    shared void specTest_Lists_279() {
        value md = "- a\n  - b\n\n    c\n- d\n";
        value html = "<ul>\n<li>a\n<ul>\n<li>\n<p>b</p>\n<p>c</p>\n</li>\n</ul>\n</li>\n<li>d</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 280 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-280"""
    test
    shared void specTest_Lists_280() {
        value md = "* a\n  > b\n  >\n* c\n";
        value html = "<ul>\n<li>a\n<blockquote>\n<p>b</p>\n</blockquote>\n</li>\n<li>c</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 281 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-281"""
    test
    shared void specTest_Lists_281() {
        value md = "- a\n  > b\n  \`\`\`\n  c\n  \`\`\`\n- d\n";
        value html = "<ul>\n<li>a\n<blockquote>\n<p>b</p>\n</blockquote>\n<pre><code>c\n</code></pre>\n</li>\n<li>d</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 282 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-282"""
    test
    shared void specTest_Lists_282() {
        value md = "- a\n";
        value html = "<ul>\n<li>a</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 283 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-283"""
    test
    shared void specTest_Lists_283() {
        value md = "- a\n  - b\n";
        value html = "<ul>\n<li>a\n<ul>\n<li>b</li>\n</ul>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 284 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-284"""
    test
    shared void specTest_Lists_284() {
        value md = "1. \`\`\`\n   foo\n   \`\`\`\n\n   bar\n";
        value html = "<ol>\n<li>\n<pre><code>foo\n</code></pre>\n<p>bar</p>\n</li>\n</ol>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 285 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-285"""
    test
    shared void specTest_Lists_285() {
        value md = "* foo\n  * bar\n\n  baz\n";
        value html = "<ul>\n<li>\n<p>foo</p>\n<ul>\n<li>bar</li>\n</ul>\n<p>baz</p>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 286 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-286"""
    test
    shared void specTest_Lists_286() {
        value md = "- a\n  - b\n  - c\n\n- d\n  - e\n  - f\n";
        value html = "<ul>\n<li>\n<p>a</p>\n<ul>\n<li>b</li>\n<li>c</li>\n</ul>\n</li>\n<li>\n<p>d</p>\n<ul>\n<li>e</li>\n<li>f</li>\n</ul>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

}
