import ceylon.test{test,assertEquals}
import ceylon.markdown.core{parse}
import ceylon.markdown.html{renderPartialHtml}
import ceylon.html{renderTemplate,Node}

/*
  The code in this file was generated by the make_tests.py script
  You might want to run it from time to time
  to keep these tests up to date with the latest
  commonmark spec tests
*/
shared class Paragraphs() {
    String render(String md) {
        value sb = StringBuilder();
        value f = sb.append;
        for (node in renderPartialHtml(parse(md))) {
            assert(is Node node);
            renderTemplate(node, f);
        }
        return sb.string;
    }

    """Test for example 180 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-180"""
    test
    shared void specTest_Paragraphs_180() {
        value md = "aaa\n\nbbb\n";
        value html = "<p>aaa</p>\n<p>bbb</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 181 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-181"""
    test
    shared void specTest_Paragraphs_181() {
        value md = "aaa\nbbb\n\nccc\nddd\n";
        value html = "<p>aaa\nbbb</p>\n<p>ccc\nddd</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 182 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-182"""
    test
    shared void specTest_Paragraphs_182() {
        value md = "aaa\n\n\nbbb\n";
        value html = "<p>aaa</p>\n<p>bbb</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 183 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-183"""
    test
    shared void specTest_Paragraphs_183() {
        value md = "  aaa\n bbb\n";
        value html = "<p>aaa\nbbb</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 184 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-184"""
    test
    shared void specTest_Paragraphs_184() {
        value md = "aaa\n             bbb\n                                       ccc\n";
        value html = "<p>aaa\nbbb\nccc</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 185 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-185"""
    test
    shared void specTest_Paragraphs_185() {
        value md = "   aaa\nbbb\n";
        value html = "<p>aaa\nbbb</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 186 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-186"""
    test
    shared void specTest_Paragraphs_186() {
        value md = "    aaa\nbbb\n";
        value html = "<pre><code>aaa\n</code></pre>\n<p>bbb</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 187 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-187"""
    test
    shared void specTest_Paragraphs_187() {
        value md = "aaa     \nbbb     \n";
        value html = "<p>aaa<br />\nbbb</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

}
