import ceylon.test{test,assertEquals}
import ceylon.markdown.core{parse}
import ceylon.markdown.html{renderPartialHtml}
import ceylon.html{renderTemplate,Node}

/*
  The code in this file was generated by the make_tests.py script
  You might want to run it from time to time
  to keep these tests up to date with the latest
  commonmark spec tests
*/
shared class Precedence() {
    String render(String md) {
        value sb = StringBuilder();
        value f = sb.append;
        for (node in renderPartialHtml(parse(md))) {
            assert(is Node node);
            renderTemplate(node, f);
        }
        return sb.string;
    }

    """Test for example 12 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-12"""
    test
    shared void specTest_Precedence_12() {
        value md = "- \`one\n- two\`\n";
        value html = "<ul>\n<li>\`one</li>\n<li>two\`</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

}
