import ceylon.test{test,assertEquals}
import ceylon.markdown.core{parse}
import ceylon.markdown.html{renderPartialHtml}
import ceylon.html{renderTemplate,Node}

/*
  The code in this file was generated by the make_tests.py script
  You might want to run it from time to time
  to keep these tests up to date with the latest
  commonmark spec tests
*/
shared class Setext_headings() {
    String render(String md) {
        value sb = StringBuilder();
        value f = sb.append;
        for (node in renderPartialHtml(parse(md))) {
            assert(is Node node);
            renderTemplate(node, f);
        }
        return sb.string;
    }

    """Test for example 50 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-50"""
    test
    shared void specTest_Setext_headings_50() {
        value md = "Foo *bar*\n=========\n\nFoo *bar*\n---------\n";
        value html = "<h1>Foo <em>bar</em></h1>\n<h2>Foo <em>bar</em></h2>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 51 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-51"""
    test
    shared void specTest_Setext_headings_51() {
        value md = "Foo *bar\nbaz*\n====\n";
        value html = "<h1>Foo <em>bar\nbaz</em></h1>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 52 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-52"""
    test
    shared void specTest_Setext_headings_52() {
        value md = "Foo\n-------------------------\n\nFoo\n=\n";
        value html = "<h2>Foo</h2>\n<h1>Foo</h1>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 53 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-53"""
    test
    shared void specTest_Setext_headings_53() {
        value md = "   Foo\n---\n\n  Foo\n-----\n\n  Foo\n  ===\n";
        value html = "<h2>Foo</h2>\n<h2>Foo</h2>\n<h1>Foo</h1>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 54 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-54"""
    test
    shared void specTest_Setext_headings_54() {
        value md = "    Foo\n    ---\n\n    Foo\n---\n";
        value html = "<pre><code>Foo\n---\n\nFoo\n</code></pre>\n<hr />\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 55 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-55"""
    test
    shared void specTest_Setext_headings_55() {
        value md = "Foo\n   ----      \n";
        value html = "<h2>Foo</h2>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 56 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-56"""
    test
    shared void specTest_Setext_headings_56() {
        value md = "Foo\n    ---\n";
        value html = "<p>Foo\n---</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 57 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-57"""
    test
    shared void specTest_Setext_headings_57() {
        value md = "Foo\n= =\n\nFoo\n--- -\n";
        value html = "<p>Foo\n= =</p>\n<p>Foo</p>\n<hr />\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 58 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-58"""
    test
    shared void specTest_Setext_headings_58() {
        value md = "Foo  \n-----\n";
        value html = "<h2>Foo</h2>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 59 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-59"""
    test
    shared void specTest_Setext_headings_59() {
        value md = "Foo\\\n----\n";
        value html = "<h2>Foo\\</h2>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 60 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-60"""
    test
    shared void specTest_Setext_headings_60() {
        value md = "\`Foo\n----\n\`\n\n<a title=\"a lot\n---\nof dashes\"/>\n";
        value html = "<h2>\`Foo</h2>\n<p>\`</p>\n<h2>&lt;a title=&quot;a lot</h2>\n<p>of dashes&quot;/&gt;</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 61 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-61"""
    test
    shared void specTest_Setext_headings_61() {
        value md = "> Foo\n---\n";
        value html = "<blockquote>\n<p>Foo</p>\n</blockquote>\n<hr />\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 62 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-62"""
    test
    shared void specTest_Setext_headings_62() {
        value md = "> foo\nbar\n===\n";
        value html = "<blockquote>\n<p>foo\nbar\n===</p>\n</blockquote>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 63 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-63"""
    test
    shared void specTest_Setext_headings_63() {
        value md = "- Foo\n---\n";
        value html = "<ul>\n<li>Foo</li>\n</ul>\n<hr />\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 64 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-64"""
    test
    shared void specTest_Setext_headings_64() {
        value md = "Foo\nBar\n---\n";
        value html = "<h2>Foo\nBar</h2>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 65 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-65"""
    test
    shared void specTest_Setext_headings_65() {
        value md = "---\nFoo\n---\nBar\n---\nBaz\n";
        value html = "<hr />\n<h2>Foo</h2>\n<h2>Bar</h2>\n<p>Baz</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 66 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-66"""
    test
    shared void specTest_Setext_headings_66() {
        value md = "\n====\n";
        value html = "<p>====</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 67 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-67"""
    test
    shared void specTest_Setext_headings_67() {
        value md = "---\n---\n";
        value html = "<hr />\n<hr />\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 68 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-68"""
    test
    shared void specTest_Setext_headings_68() {
        value md = "- foo\n-----\n";
        value html = "<ul>\n<li>foo</li>\n</ul>\n<hr />\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 69 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-69"""
    test
    shared void specTest_Setext_headings_69() {
        value md = "    foo\n---\n";
        value html = "<pre><code>foo\n</code></pre>\n<hr />\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 70 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-70"""
    test
    shared void specTest_Setext_headings_70() {
        value md = "> foo\n-----\n";
        value html = "<blockquote>\n<p>foo</p>\n</blockquote>\n<hr />\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 71 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-71"""
    test
    shared void specTest_Setext_headings_71() {
        value md = "\\> foo\n------\n";
        value html = "<h2>&gt; foo</h2>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 72 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-72"""
    test
    shared void specTest_Setext_headings_72() {
        value md = "Foo\n\nbar\n---\nbaz\n";
        value html = "<p>Foo</p>\n<h2>bar</h2>\n<p>baz</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 73 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-73"""
    test
    shared void specTest_Setext_headings_73() {
        value md = "Foo\nbar\n\n---\n\nbaz\n";
        value html = "<p>Foo\nbar</p>\n<hr />\n<p>baz</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 74 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-74"""
    test
    shared void specTest_Setext_headings_74() {
        value md = "Foo\nbar\n* * *\nbaz\n";
        value html = "<p>Foo\nbar</p>\n<hr />\n<p>baz</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 75 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-75"""
    test
    shared void specTest_Setext_headings_75() {
        value md = "Foo\nbar\n\\---\nbaz\n";
        value html = "<p>Foo\nbar\n---\nbaz</p>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

}
