import ceylon.test{test,assertEquals}
import ceylon.markdown.core{parse}
import ceylon.markdown.html{renderPartialHtml}
import ceylon.html{renderTemplate,Node}

/*
  The code in this file was generated by the make_tests.py script
  You might want to run it from time to time
  to keep these tests up to date with the latest
  commonmark spec tests
*/
shared class Tabs() {
    String render(String md) {
        value sb = StringBuilder();
        value f = sb.append;
        for (node in renderPartialHtml(parse(md))) {
            assert(is Node node);
            renderTemplate(node, f);
        }
        return sb.string;
    }

    """Test for example 1 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-1"""
    test
    shared void specTest_Tabs_1() {
        value md = "	foo	baz		bim\n";
        value html = "<pre><code>foo	baz		bim\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 2 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-2"""
    test
    shared void specTest_Tabs_2() {
        value md = "  	foo	baz		bim\n";
        value html = "<pre><code>foo	baz		bim\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 3 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-3"""
    test
    shared void specTest_Tabs_3() {
        value md = "    a	a\n    ὐ	a\n";
        value html = "<pre><code>a	a\nὐ	a\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 4 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-4"""
    test
    shared void specTest_Tabs_4() {
        value md = "  - foo\n\n	bar\n";
        value html = "<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 5 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-5"""
    test
    shared void specTest_Tabs_5() {
        value md = "- foo\n\n		bar\n";
        value html = "<ul>\n<li>\n<p>foo</p>\n<pre><code>  bar\n</code></pre>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 6 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-6"""
    test
    shared void specTest_Tabs_6() {
        value md = ">		foo\n";
        value html = "<blockquote>\n<pre><code>  foo\n</code></pre>\n</blockquote>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 7 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-7"""
    test
    shared void specTest_Tabs_7() {
        value md = "-		foo\n";
        value html = "<ul>\n<li>\n<pre><code>  foo\n</code></pre>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 8 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-8"""
    test
    shared void specTest_Tabs_8() {
        value md = "    foo\n	bar\n";
        value html = "<pre><code>foo\nbar\n</code></pre>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 9 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-9"""
    test
    shared void specTest_Tabs_9() {
        value md = " - foo\n   - bar\n	 - baz\n";
        value html = "<ul>\n<li>foo\n<ul>\n<li>bar\n<ul>\n<li>baz</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 10 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-10"""
    test
    shared void specTest_Tabs_10() {
        value md = "#	Foo\n";
        value html = "<h1>Foo</h1>\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

    """Test for example 11 from the common mark spec (v0.26).
       See http://spec.commonmark.org/0.26/#example-11"""
    test
    shared void specTest_Tabs_11() {
        value md = "*	*	*	\n";
        value html = "<hr />\n";
        assertEquals{
            expected = html;
            actual = render(md);
        };
    }

}
